/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pa_2019_02_01_aplicacionalumnovisual;

import java.text.DecimalFormat;
import java.util.Random;

/**
 *
 * @author aa534
 */
public class JFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextAlumno1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextAsist1 = new javax.swing.JTextField();
        jTextTareas1 = new javax.swing.JTextField();
        jTextPro1 = new javax.swing.JTextField();
        jTextExamen1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabCalif1 = new javax.swing.JLabel();
        jTextExamen2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabCalif2 = new javax.swing.JLabel();
        jTextAlumno2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextAsist2 = new javax.swing.JTextField();
        jTextTareas2 = new javax.swing.JTextField();
        jTextPro2 = new javax.swing.JTextField();
        jLabPromAsist = new javax.swing.JLabel();
        jLabPromTareas = new javax.swing.JLabel();
        jLabPromExamen = new javax.swing.JLabel();
        jLabPromGral = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButCalcular = new javax.swing.JButton();
        jButAleatorios = new javax.swing.JButton();
        jButBorrar = new javax.swing.JButton();
        jLabPromPro = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextAsist3 = new javax.swing.JTextField();
        jTextTareas3 = new javax.swing.JTextField();
        jTextPro3 = new javax.swing.JTextField();
        jTextExamen3 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabCalif3 = new javax.swing.JLabel();
        jTextAlumno3 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabMejor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Alumno");

        jLabel2.setText("Asist");

        jLabel3.setText("Tareas");

        jLabel4.setText("Prouecto");

        jLabel5.setText("Examen");

        jLabel6.setText("Calificación");

        jLabCalif1.setBackground(new java.awt.Color(51, 204, 0));
        jLabCalif1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabCalif1.setOpaque(true);

        jLabel8.setText("Calificación");

        jLabel9.setText("Alumno");

        jLabCalif2.setBackground(new java.awt.Color(0, 204, 51));
        jLabCalif2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabCalif2.setOpaque(true);

        jLabel11.setText("Asist");

        jLabel12.setText("Tareas");

        jLabel13.setText("Prouecto");

        jLabel14.setText("Examen");

        jLabPromAsist.setBackground(new java.awt.Color(255, 102, 102));
        jLabPromAsist.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabPromAsist.setOpaque(true);

        jLabPromTareas.setBackground(new java.awt.Color(255, 102, 102));
        jLabPromTareas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabPromTareas.setOpaque(true);

        jLabPromExamen.setBackground(new java.awt.Color(255, 102, 102));
        jLabPromExamen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabPromExamen.setOpaque(true);

        jLabPromGral.setBackground(new java.awt.Color(51, 153, 255));
        jLabPromGral.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabPromGral.setForeground(new java.awt.Color(255, 255, 255));
        jLabPromGral.setOpaque(true);

        jLabel27.setText("Promedios");

        jButCalcular.setText("Calcular");
        jButCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalcularActionPerformed(evt);
            }
        });

        jButAleatorios.setText("Aleatorios");
        jButAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatoriosActionPerformed(evt);
            }
        });

        jButBorrar.setText("Borrar");
        jButBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButBorrarActionPerformed(evt);
            }
        });

        jLabPromPro.setBackground(new java.awt.Color(255, 102, 102));
        jLabPromPro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabPromPro.setOpaque(true);

        jLabel29.setText("Examen");

        jLabel30.setText("Calificación");

        jLabel31.setText("Alumno");

        jLabCalif3.setBackground(new java.awt.Color(0, 204, 51));
        jLabCalif3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabCalif3.setOpaque(true);

        jLabel33.setText("Asist");

        jLabel34.setText("Tareas");

        jLabel35.setText("Prouecto");

        jLabMejor.setBackground(new java.awt.Color(204, 204, 0));
        jLabMejor.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextAlumno1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jTextAsist1)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTextTareas1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel13)
                            .addComponent(jLabel35)
                            .addComponent(jTextPro1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextPro3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTextExamen1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabCalif1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel9))
                                    .addComponent(jTextAlumno2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel11))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jTextAsist2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextTareas3)
                                            .addComponent(jTextTareas2))
                                        .addGap(89, 89, 89)))
                                .addComponent(jLabel14)
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabCalif2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel31)
                                        .addGap(63, 63, 63)
                                        .addComponent(jLabel33))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextAlumno3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)
                                        .addComponent(jTextAsist3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel34)
                                .addGap(28, 28, 28)
                                .addComponent(jTextPro2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextExamen3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabCalif3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextExamen2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel30))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabPromTareas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(218, 218, 218))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabPromExamen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabPromGral, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabPromPro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabMejor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButCalcular)
                                .addGap(18, 18, 18)
                                .addComponent(jButAleatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButBorrar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(18, 18, 18)
                                .addComponent(jLabPromAsist, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabCalif1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextAlumno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextAsist1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextTareas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextPro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextExamen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabCalif2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextAlumno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextAsist2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextTareas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextPro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextExamen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabCalif3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextAlumno3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextAsist3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextTareas3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextPro3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextExamen3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabPromPro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabPromExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabPromTareas, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabPromAsist, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(jLabPromGral, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButCalcular)
                    .addComponent(jButAleatorios)
                    .addComponent(jButBorrar))
                .addGap(18, 18, 18)
                .addComponent(jLabMejor, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalcularActionPerformed
        // TODO add your handling code here:
        
        DecimalFormat f = new DecimalFormat("###.00");
        
        int asist, tareas, proy, examen;
        Alumno uno = new Alumno();
        asist = Integer.parseInt(jTextAsist1.getText());
        tareas = Integer.parseInt(jTextTareas1.getText());
        proy = Integer.parseInt(jTextPro1.getText());
        examen = Integer.parseInt(jTextExamen1.getText());
        
        uno.setNombre(jTextAlumno1.getText());
        uno.setAsistencias(asist);
        uno.setTareas(tareas);
        uno.setProyectos(proy);
        uno.setExamen(examen);
        
        jLabCalif1.setText(f.format(uno.Calificacion()));
        
        
        Alumno dos = new Alumno(jTextAlumno2.getText(),
                                Integer.parseInt(jTextAsist2.getText()),
                                Integer.parseInt(jTextTareas2.getText()),
                                Integer.parseInt(jTextPro2.getText()),
                                Integer.parseInt(jTextExamen2.getText())
                                );
        jLabCalif2.setText(f.format(dos.Calificacion()));
        
        
        Alumno tres = new Alumno(uno);
        
        tres.setNombre(jTextAlumno3.getText());
        tres.setAsistencias(Integer.parseInt(jTextAsist3.getText()));
        tres.setTareas(Integer.parseInt(jTextTareas3.getText()));
        tres.setProyectos(Integer.parseInt(jTextPro3.getText()));
        tres.setExamen(Integer.parseInt(jTextExamen3.getText()));//los metodos estaticos son los que se pueden utilizar sin crear objetos de la clase
        
        jLabCalif3.setText(f.format(tres.Calificacion()));
        
        
        double promAsist, promTareas, promProy, promExamen, promGral;
        promAsist = (double)(uno.getAsistencias()+dos.getAsistencias()+tres.getAsistencias())/3;
        promTareas = (double)(uno.getTareas()+dos.getTareas()+tres.getTareas())/3;
        promProy = (double)(uno.getProyectos()+dos.getProyectos()+tres.getProyectos())/3;
        promExamen = (double)(uno.getExamen()+dos.getExamen()+tres.getExamen())/3;
        promGral = (double)(uno.Calificacion()+dos.Calificacion()+tres.Calificacion())/3;
        
        
        jLabPromAsist.setText(f.format(promAsist));
        jLabPromTareas.setText(f.format(promTareas));
        jLabPromPro.setText(f.format(promProy));
        jLabPromExamen.setText(f.format(promExamen));
        jLabPromGral.setText(f.format(promGral));
        
        String mejor;
        if(uno.Calificacion() > dos.Calificacion())
            if(uno.Calificacion() > tres.Calificacion())
                mejor = uno.getNombre();
            else
                mejor = tres.getNombre();
        else 
            if(dos.Calificacion() > tres.Calificacion())
                mejor = dos.getNombre();
            else
                mejor = tres.getNombre();
        
        jLabMejor.setText("El mejor alumno es: "+mejor);
        
    }//GEN-LAST:event_jButCalcularActionPerformed

    private void jButBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButBorrarActionPerformed
        // TODO add your handling code here:
        jTextAlumno1.setText("");
        jTextAlumno2.setText("");
        jTextAlumno3.setText("");
        
        jTextAsist1.setText("");
        jTextAsist2.setText("");
        jTextAsist3.setText("");
        
        jTextTareas1.setText("");
        jTextTareas2.setText("");
        jTextTareas3.setText("");
        
        jTextPro1.setText("");
        jTextPro2.setText("");
        jTextPro3.setText("");
        
        jTextExamen1.setText("");
        jTextExamen2.setText("");
        jTextExamen3.setText("");
        
        jLabCalif1.setText("");
        jLabCalif2.setText("");
        jLabCalif3.setText("");
        
        jLabPromAsist.setText("");
        jLabPromTareas.setText("");
        jLabPromPro.setText("");
        jLabPromExamen.setText("");
        
        jLabPromGral.setText("");
        
    }//GEN-LAST:event_jButBorrarActionPerformed

    private void jButAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatoriosActionPerformed
        // TODO add your handling code here:
        String [] nom = {"Juan", "Maria", "Pedro", "Luis", "Diana", "Martha", "Sofia", "Mario", "Raul"};
        String [] ape = {"Lopez","Perez", "Gomez","Ruiz", "Mendez", "Aguilera","Garcia","Montes","Hernandez"};
        Random azar = new Random();
        
        jTextAlumno1.setText(nom[azar.nextInt(nom.length)]+" "+ape[azar.nextInt(ape.length)]);
        jTextAlumno2.setText(nom[azar.nextInt(nom.length)]+" "+ape[azar.nextInt(ape.length)]);
        jTextAlumno3.setText(nom[azar.nextInt(nom.length)]+" "+ape[azar.nextInt(ape.length)]);
        
        jTextAsist1.setText(40+azar.nextInt(61)+"");
        jTextAsist2.setText(40+azar.nextInt(61)+"");
        jTextAsist3.setText(40+azar.nextInt(61)+"");
        
        jTextTareas1.setText(40+azar.nextInt(61)+"");
        jTextTareas2.setText(40+azar.nextInt(61)+"");
        jTextTareas3.setText(40+azar.nextInt(61)+"");
        
        jTextPro1.setText(40+azar.nextInt(61)+"");
        jTextPro2.setText(40+azar.nextInt(61)+"");
        jTextPro3.setText(40+azar.nextInt(61)+"");
        
        jTextExamen1.setText(40+azar.nextInt(61)+"");
        jTextExamen2.setText(40+azar.nextInt(61)+"");
        jTextExamen3.setText(40+azar.nextInt(61)+"");
        
        
    }//GEN-LAST:event_jButAleatoriosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAleatorios;
    private javax.swing.JButton jButBorrar;
    private javax.swing.JButton jButCalcular;
    private javax.swing.JLabel jLabCalif1;
    private javax.swing.JLabel jLabCalif2;
    private javax.swing.JLabel jLabCalif3;
    private javax.swing.JLabel jLabMejor;
    private javax.swing.JLabel jLabPromAsist;
    private javax.swing.JLabel jLabPromExamen;
    private javax.swing.JLabel jLabPromGral;
    private javax.swing.JLabel jLabPromPro;
    private javax.swing.JLabel jLabPromTareas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextAlumno1;
    private javax.swing.JTextField jTextAlumno2;
    private javax.swing.JTextField jTextAlumno3;
    private javax.swing.JTextField jTextAsist1;
    private javax.swing.JTextField jTextAsist2;
    private javax.swing.JTextField jTextAsist3;
    private javax.swing.JTextField jTextExamen1;
    private javax.swing.JTextField jTextExamen2;
    private javax.swing.JTextField jTextExamen3;
    private javax.swing.JTextField jTextPro1;
    private javax.swing.JTextField jTextPro2;
    private javax.swing.JTextField jTextPro3;
    private javax.swing.JTextField jTextTareas1;
    private javax.swing.JTextField jTextTareas2;
    private javax.swing.JTextField jTextTareas3;
    // End of variables declaration//GEN-END:variables
}
