/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pa_18131209_proyecto_01;

import java.util.Random;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author José Misael Adame Sandoval
 */

// Es un JFrame que se encuentra encapsulado
public class PA_18131209_Frame_01 extends javax.swing.JFrame {

    /**
     * Creates new form PA_18131209_Frame_01
     */
    
    ConjuntoCircuitos lista;
    
    public PA_18131209_Frame_01() 
    {
        initComponents();
        // Deshabilita los botones
        this.deshabilitar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabImaAsignacion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextImpedancia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextReacInductiva = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextReacCapacitiva = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCircuito = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jSpinPosicion = new javax.swing.JSpinner();
        jButGrabar = new javax.swing.JButton();
        jButAlfabetico = new javax.swing.JButton();
        jButDescendente = new javax.swing.JButton();
        jCheckBoxIncrementar = new javax.swing.JCheckBox();
        jButAleatorio = new javax.swing.JButton();
        jButEjemplo1 = new javax.swing.JButton();
        jButEditar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButMayorYMenor = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabMayor = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabTotalImp = new javax.swing.JLabel();
        jLabPromedioResist = new javax.swing.JLabel();
        jLabTotalReacInductiva = new javax.swing.JLabel();
        jLabPromedioReacCapacitiva = new javax.swing.JLabel();
        jLabMenor = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextNoCircuitos = new javax.swing.JTextField();
        jButAjustar = new javax.swing.JButton();
        jButEjemplo3 = new javax.swing.JButton();
        jButEjemplo2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabImaAsignacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pa_18131209_proyecto_01/AsignacionProyecto.jpg"))); // NOI18N

        jLabel1.setText("Nombre");

        jTextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreActionPerformed(evt);
            }
        });

        jLabel2.setText("Impedancia (Z)");

        jTextImpedancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextImpedanciaActionPerformed(evt);
            }
        });

        jLabel3.setText("Reactancia inductiva (XL)");

        jTextReacInductiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextReacInductivaActionPerformed(evt);
            }
        });

        jLabel4.setText("Reactancia Capacitiva (XC)");

        jTextReacCapacitiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextReacCapacitivaActionPerformed(evt);
            }
        });

        jTableCircuito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Impedancia (Z)", "Reactancia Inductiva (XL)", "Reactancia Capacitiva (XC)", "Resistencia (R)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableCircuito);
        if (jTableCircuito.getColumnModel().getColumnCount() > 0) {
            jTableCircuito.getColumnModel().getColumn(0).setResizable(false);
            jTableCircuito.getColumnModel().getColumn(1).setResizable(false);
            jTableCircuito.getColumnModel().getColumn(2).setResizable(false);
            jTableCircuito.getColumnModel().getColumn(3).setResizable(false);
            jTableCircuito.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel5.setText("Posición");

        jSpinPosicion.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jButGrabar.setText("Grabar");
        jButGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButGrabarActionPerformed(evt);
            }
        });

        jButAlfabetico.setText("Alfabetico");
        jButAlfabetico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAlfabeticoActionPerformed(evt);
            }
        });

        jButDescendente.setText("Descendente");
        jButDescendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDescendenteActionPerformed(evt);
            }
        });

        jCheckBoxIncrementar.setText("Incrementar");

        jButAleatorio.setText("Aleatorio");
        jButAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatorioActionPerformed(evt);
            }
        });

        jButEjemplo1.setText("Ejemplo 1");
        jButEjemplo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEjemplo1ActionPerformed(evt);
            }
        });

        jButEditar.setText("Editar");
        jButEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEditarActionPerformed(evt);
            }
        });

        jLabel6.setText("Total de Impedancia");

        jLabel7.setText("Promedio de Resistencia ");

        jLabel8.setText("Total de Reactancia Inductiva");

        jLabel9.setText("Promedio de Reactancia Capacitiva");

        jButMayorYMenor.setText("Mayor y Menor");
        jButMayorYMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButMayorYMenorActionPerformed(evt);
            }
        });

        jLabel10.setText("Mayor");

        jLabel11.setText("Menor");

        jLabMayor.setBackground(new java.awt.Color(255, 102, 102));
        jLabMayor.setOpaque(true);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pa_18131209_proyecto_01/Informacion.jpg"))); // NOI18N

        jLabTotalImp.setBackground(new java.awt.Color(204, 255, 204));
        jLabTotalImp.setOpaque(true);

        jLabPromedioResist.setBackground(new java.awt.Color(204, 255, 204));
        jLabPromedioResist.setOpaque(true);

        jLabTotalReacInductiva.setBackground(new java.awt.Color(204, 255, 204));
        jLabTotalReacInductiva.setOpaque(true);

        jLabPromedioReacCapacitiva.setBackground(new java.awt.Color(204, 255, 204));
        jLabPromedioReacCapacitiva.setOpaque(true);

        jLabMenor.setBackground(new java.awt.Color(255, 102, 102));
        jLabMenor.setOpaque(true);

        jLabel12.setText("No. De Circuitos");

        jTextNoCircuitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNoCircuitosActionPerformed(evt);
            }
        });

        jButAjustar.setText("Ajustar");
        jButAjustar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAjustarActionPerformed(evt);
            }
        });

        jButEjemplo3.setText("Ejemplo 3");
        jButEjemplo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEjemplo3ActionPerformed(evt);
            }
        });

        jButEjemplo2.setText("Ejemplo 2");
        jButEjemplo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEjemplo2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabImaAsignacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextNoCircuitos))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextImpedancia, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextReacInductiva, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextReacCapacitiva, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jSpinPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 12, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButAjustar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButGrabar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButDescendente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButAleatorio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButAlfabetico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButEditar)
                                .addGap(22, 22, 22)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButEjemplo3)
                                .addGap(43, 43, 43))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jButEjemplo1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButEjemplo2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(jCheckBoxIncrementar)))
                                .addGap(0, 13, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabTotalImp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabPromedioResist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabTotalReacInductiva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabPromedioReacCapacitiva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButMayorYMenor)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jLabMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jLabMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabImaAsignacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButAjustar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButDescendente)
                                    .addComponent(jButAlfabetico)
                                    .addComponent(jButGrabar)
                                    .addComponent(jButAleatorio)
                                    .addComponent(jButEditar)
                                    .addComponent(jButEjemplo1)
                                    .addComponent(jButEjemplo2))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)))
                            .addComponent(jButEjemplo3, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextNoCircuitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextImpedancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextReacInductiva))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextReacCapacitiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSpinPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBoxIncrementar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabTotalImp, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabPromedioResist, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabTotalReacInductiva, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabPromedioReacCapacitiva, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButMayorYMenor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // metodo para la deshabilitación de botones y textos
    public void deshabilitar() 
    {
        jButAleatorio.setEnabled(false);
        jButGrabar.setEnabled(false);
        jButDescendente.setEnabled(false);
        jButAleatorio.setEnabled(false);
        jButEditar.setEnabled(false);
        jButMayorYMenor.setEnabled(false);
        jButEjemplo1.setEnabled(false);
        jButEjemplo2.setEnabled(false);
        jButEjemplo3.setEnabled(false);
        jButAlfabetico.setEnabled(false);
        jTextNombre.setEnabled(false);
        jTextImpedancia.setEnabled(false);
        jTextReacInductiva.setEnabled(false);
        jTextReacCapacitiva.setEnabled(false);
        jSpinPosicion.setEnabled(false);
        jCheckBoxIncrementar.setEnabled(false);
    }
    
    // metodo para habilitar los botones al dar clic en el botón de Ajustes
    public void habilitarAlAjuste() 
    {
        jButGrabar.setEnabled(true);
        jButEjemplo1.setEnabled(true);
        jButEjemplo2.setEnabled(true);
        jButEjemplo3.setEnabled(true);
        jButAleatorio.setEnabled(true);
        jTextNombre.setEnabled(true);
        jTextImpedancia.setEnabled(true);
        jTextReacInductiva.setEnabled(true);
        jTextReacCapacitiva.setEnabled(true);
        jSpinPosicion.setEnabled(true);
        jCheckBoxIncrementar.setEnabled(true);
    }
    
    // método para habilitar los botones al dar clic en el botón de Grabar
    public void habilitarAlGrabar() 
    {
        jButAleatorio.setEnabled(true);
        jButDescendente.setEnabled(true);
        jButAlfabetico.setEnabled(true);
        jButAleatorio.setEnabled(true);
        jButEditar.setEnabled(true);
        jButMayorYMenor.setEnabled(true);
    }
    
    // No hace nada
    private void jTextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreActionPerformed
    
    // No hace nada
    private void jTextImpedanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextImpedanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextImpedanciaActionPerformed
    
    // No hace nada
    private void jTextReacInductivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextReacInductivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextReacInductivaActionPerformed
   
    // No hace nada
    private void jTextReacCapacitivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextReacCapacitivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextReacCapacitivaActionPerformed
    
    // El Boton de Ejemplo 1
    private void jButEjemplo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEjemplo1ActionPerformed
        // TODO add your handling code here:

        // Se sustituyen los valores de ejemplo en los campos de texto
        jTextNombre.setText("M-18");
        jTextImpedancia.setText(51.4198+"");
        jTextReacInductiva.setText(15+"");
        jTextReacCapacitiva.setText(3+"");
    }//GEN-LAST:event_jButEjemplo1ActionPerformed
   
    // El Boton de grabar
    private void jButGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButGrabarActionPerformed
        // TODO add your handling code here:
       
        // Declaracion del arreglo
        Circuito x = new Circuito();
        
        int posicion = (int)jSpinPosicion.getValue() - 1;
        
        x.setNombre(jTextNombre.getText());
        x.setImpedancia(Double.parseDouble(jTextImpedancia.getText()));
        x.setReactanciaInductiva(Double.parseDouble(jTextReacInductiva.getText()));
        x.setReactanciaCapacitiva(Double.parseDouble(jTextReacCapacitiva.getText()));
        
        // Llama los métodos 
        lista.setCircuito(x, posicion);
        
        lista.mostrar(jTableCircuito, jLabTotalImp, jLabPromedioResist, 
                      jLabTotalReacInductiva, jLabPromedioReacCapacitiva);
        
        // Condicion cuando el CheckBox llega hasta al límite de los circuitos
        if (jCheckBoxIncrementar.isSelected())
            if (posicion == lista.getTamaño()-1)
                jSpinPosicion.setValue(1);
            else
                jSpinPosicion.setValue(posicion+2);          
        
        // Habilita todos los botones
        this.habilitarAlGrabar();
    }//GEN-LAST:event_jButGrabarActionPerformed

    // El Boton Aleatorio
    private void jButAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatorioActionPerformed
        // TODO add your handling code here:
        
        // Declaracion de la variable azar
        Random azar = new Random();
        
        // Coloca los textos en los campos de texto de manera aleatoria
        jTextNombre.setText(Nombre.nextNombre());
        jTextImpedancia.setText(50+azar.nextInt(100)+"");
        jTextReacInductiva.setText(azar.nextInt(50)+"");
        jTextReacCapacitiva.setText(azar.nextInt(49)+"");
    }//GEN-LAST:event_jButAleatorioActionPerformed

    // El Boton de Ordenar Descendentemente por Resistencia
    private void jButDescendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDescendenteActionPerformed
        // TODO add your handling code here:
        
        
        lista.ordenarResistencia();
        
        lista.mostrar(jTableCircuito, jLabTotalImp, jLabPromedioResist, 
                      jLabTotalReacInductiva, jLabPromedioReacCapacitiva);
    }//GEN-LAST:event_jButDescendenteActionPerformed

    // El Boton que ordena por alfabeto el nombre del circuito
    private void jButAlfabeticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAlfabeticoActionPerformed
        // TODO add your handling code here:
        lista.ordenarAlfabetico();
       
        lista.mostrar(jTableCircuito, jLabTotalImp, jLabPromedioResist, 
                      jLabTotalReacInductiva, jLabPromedioReacCapacitiva);

    }//GEN-LAST:event_jButAlfabeticoActionPerformed

    // El Boton para Editar valores de una fila
    private void jButEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEditarActionPerformed
        // TODO add your handling code here:
        int posicion = (int)jSpinPosicion.getValue() - 1;
        
        Circuito x = lista.getCircuito(posicion);
        
        jTextNombre.setText(x.getNombre());
        jTextImpedancia.setText(x.getImpedancia()+"");
        jTextReacInductiva.setText(x.getReactanciaInductiva()+"");
        jTextReacCapacitiva.setText(x.getReactanciaCapacitiva()+"");
        

    }//GEN-LAST:event_jButEditarActionPerformed

    // Boton que dice el nombre del mayor y menor circuito por la Resistencia
    private void jButMayorYMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButMayorYMenorActionPerformed
        // TODO add your handling code here:
        jLabMayor.setText(lista.mayor().getNombre());
        jLabMenor.setText(lista.menor().getNombre());
    }//GEN-LAST:event_jButMayorYMenorActionPerformed

    // No hace nada
    private void jTextNoCircuitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNoCircuitosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNoCircuitosActionPerformed

    // El Boton para ajustar el número de circuitos 
    private void jButAjustarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAjustarActionPerformed
        // TODO add your handling code here:
       
        DefaultTableModel modelo = (DefaultTableModel)jTableCircuito.getModel();
        modelo.setRowCount(Integer.parseInt(jTextNoCircuitos.getText()));
        this.lista = new ConjuntoCircuitos(Integer.parseInt(jTextNoCircuitos.getText()));
        // Habilita los campos de texto y algunos botones
        this.habilitarAlAjuste();
        
    }//GEN-LAST:event_jButAjustarActionPerformed

    // El Boton del Ejemplo 3
    private void jButEjemplo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEjemplo3ActionPerformed
        // TODO add your handling code here:
        
        // Se sustituyen los valores de ejemplo en los campos de texto
        jTextNombre.setText("F-45");
        jTextImpedancia.setText(91.3017+"");
        jTextReacInductiva.setText(45+"");
        jTextReacCapacitiva.setText(1+"");
    }//GEN-LAST:event_jButEjemplo3ActionPerformed

    // El Boton del Ejemplo 2
    private void jButEjemplo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEjemplo2ActionPerformed
        // TODO add your handling code here:
        
        // Se sustituyen los valores de ejemplo en los campos de texto
        jTextNombre.setText("C-12");
        jTextImpedancia.setText(34.4093+"");
        jTextReacInductiva.setText(30+"");
        jTextReacCapacitiva.setText(2+"");
    }//GEN-LAST:event_jButEjemplo2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PA_18131209_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PA_18131209_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PA_18131209_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PA_18131209_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PA_18131209_Frame_01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAjustar;
    private javax.swing.JButton jButAleatorio;
    private javax.swing.JButton jButAlfabetico;
    private javax.swing.JButton jButDescendente;
    private javax.swing.JButton jButEditar;
    private javax.swing.JButton jButEjemplo1;
    private javax.swing.JButton jButEjemplo2;
    private javax.swing.JButton jButEjemplo3;
    private javax.swing.JButton jButGrabar;
    private javax.swing.JButton jButMayorYMenor;
    private javax.swing.JCheckBox jCheckBoxIncrementar;
    private javax.swing.JLabel jLabImaAsignacion;
    private javax.swing.JLabel jLabMayor;
    private javax.swing.JLabel jLabMenor;
    private javax.swing.JLabel jLabPromedioReacCapacitiva;
    private javax.swing.JLabel jLabPromedioResist;
    private javax.swing.JLabel jLabTotalImp;
    private javax.swing.JLabel jLabTotalReacInductiva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinPosicion;
    private javax.swing.JTable jTableCircuito;
    private javax.swing.JTextField jTextImpedancia;
    private javax.swing.JTextField jTextNoCircuitos;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextReacCapacitiva;
    private javax.swing.JTextField jTextReacInductiva;
    // End of variables declaration//GEN-END:variables
}
