/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pa_2019_03_27_aplicacionnominaempleados;

import java.awt.Color;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author alope
 */
public class JFrameRegistro extends javax.swing.JFrame {

    /**
     * Creates new form JFrameRegistro
     */
    JFrameMenu jfMenu;
    MiRandom azar = new MiRandom();
    
    public JFrameRegistro(JFrameMenu jfm) {
        initComponents();
        
        jfMenu = jfm;
        
        jRBEmpleado.setSelected(true);
        ocultar();
        
        jLabEmpReg.setText(jfMenu.getEmpleadosRegistrados()+"");
        jLabEmpTot.setText("Capcidad:"+jfMenu.getTamaño()+"    Vacantes:"+(jfMenu.getTamaño()-jfMenu.getEmpleadosRegistrados()));
    }

    public void ocultar()
    {
        jLabPiezas.setVisible(false);
        jLabPrecio.setVisible(false);
        jLabVentas.setVisible(false);
        jLabComision.setVisible(false);
        jLabDias.setVisible(false);
        jLabSueldo.setVisible(false);
        jLabBono.setVisible(false);

        jTextPiezas.setVisible(false);
        jTextPrecio.setVisible(false);
        jTextVentas.setVisible(false);
        jTextComision.setVisible(false);
        jTextDias.setVisible(false);
        jTextSueldo.setVisible(false);
        jTextBono.setVisible(false);
        
        jTextNumero.setText("");
        jTextNombre.setText("");
        jTextPiezas.setText("");
        jTextPrecio.setText("");
        jTextVentas.setText("");
        jTextComision.setText("");
        jTextDias.setText("");
        jTextSueldo.setText("");
        jTextBono.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabEmpReg = new javax.swing.JLabel();
        jRBEmpleado = new javax.swing.JRadioButton();
        jRBTaller = new javax.swing.JRadioButton();
        jRBVentas = new javax.swing.JRadioButton();
        jRBAdmin = new javax.swing.JRadioButton();
        jRBEjecutivo = new javax.swing.JRadioButton();
        jButAleatorios = new javax.swing.JButton();
        jButGrabar = new javax.swing.JButton();
        jButCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextNumero = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jLabPiezas = new javax.swing.JLabel();
        jTextPiezas = new javax.swing.JTextField();
        jLabPrecio = new javax.swing.JLabel();
        jTextPrecio = new javax.swing.JTextField();
        jLabComision = new javax.swing.JLabel();
        jTextComision = new javax.swing.JTextField();
        jLabVentas = new javax.swing.JLabel();
        jTextVentas = new javax.swing.JTextField();
        jLabSueldo = new javax.swing.JLabel();
        jTextSueldo = new javax.swing.JTextField();
        jLabDias = new javax.swing.JLabel();
        jTextDias = new javax.swing.JTextField();
        jLabBono = new javax.swing.JLabel();
        jTextBono = new javax.swing.JTextField();
        jLabEmpTot = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Registro de empleados");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 13, 256, -1));

        jButRegresar.setText("Regresar");
        jButRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 286, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Empleados registrados");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 286, -1, -1));

        jLabEmpReg.setBackground(new java.awt.Color(255, 255, 0));
        jLabEmpReg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabEmpReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabEmpReg.setOpaque(true);
        getContentPane().add(jLabEmpReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 160, 39));

        buttonGroup1.add(jRBEmpleado);
        jRBEmpleado.setText("Empleado");
        jRBEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(jRBEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 51, -1, -1));

        buttonGroup1.add(jRBTaller);
        jRBTaller.setText("Taller");
        jRBTaller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBTallerActionPerformed(evt);
            }
        });
        getContentPane().add(jRBTaller, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 51, -1, -1));

        buttonGroup1.add(jRBVentas);
        jRBVentas.setText("Ventas");
        jRBVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBVentasActionPerformed(evt);
            }
        });
        getContentPane().add(jRBVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 51, -1, -1));

        buttonGroup1.add(jRBAdmin);
        jRBAdmin.setText("Administrativo");
        jRBAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBAdminActionPerformed(evt);
            }
        });
        getContentPane().add(jRBAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 51, -1, -1));

        buttonGroup1.add(jRBEjecutivo);
        jRBEjecutivo.setText("Ejecutivo");
        jRBEjecutivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBEjecutivoActionPerformed(evt);
            }
        });
        getContentPane().add(jRBEjecutivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 51, -1, -1));

        jButAleatorios.setText("Aleatorios");
        jButAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatoriosActionPerformed(evt);
            }
        });
        getContentPane().add(jButAleatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 254, -1, -1));

        jButGrabar.setText("Grabar");
        jButGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButGrabarActionPerformed(evt);
            }
        });
        getContentPane().add(jButGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 254, -1, -1));

        jButCancelar.setText("Cancelar");
        getContentPane().add(jButCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 254, -1, -1));

        jLabel3.setText("Número");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        getContentPane().add(jTextNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 54, -1));

        jLabel4.setText("Nombre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));
        getContentPane().add(jTextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 158, -1));

        jLabPiezas.setText("Piezas");
        getContentPane().add(jLabPiezas, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 137, -1, -1));
        getContentPane().add(jTextPiezas, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 134, 57, -1));

        jLabPrecio.setText("Precio Unitario $");
        getContentPane().add(jLabPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 137, -1, -1));
        getContentPane().add(jTextPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 134, 57, -1));

        jLabComision.setText("% Comisión");
        getContentPane().add(jLabComision, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 166, -1, -1));
        getContentPane().add(jTextComision, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 163, 63, -1));

        jLabVentas.setText("Ventas $");
        getContentPane().add(jLabVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 166, -1, -1));
        getContentPane().add(jTextVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 163, 63, -1));

        jLabSueldo.setText("Sueldo diario $");
        getContentPane().add(jLabSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 201, -1, -1));
        getContentPane().add(jTextSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 198, 70, -1));

        jLabDias.setText("Días trabajados");
        getContentPane().add(jLabDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 201, -1, -1));
        getContentPane().add(jTextDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 198, 42, -1));

        jLabBono.setText("Bono $");
        jLabBono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabBonoMouseEntered(evt);
            }
        });
        getContentPane().add(jLabBono, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 201, -1, -1));
        getContentPane().add(jTextBono, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 198, 70, -1));

        jLabEmpTot.setBackground(new java.awt.Color(51, 255, 204));
        jLabEmpTot.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabEmpTot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabEmpTot.setOpaque(true);
        getContentPane().add(jLabEmpTot, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 360, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRegresarActionPerformed
        // TODO add your handling code here:
        
        FileWriter fw = null;
        PrintWriter pw = null;
        
        try {
            fw = new FileWriter(jfMenu.getArchivo());
            pw = new PrintWriter(fw);
            
            pw.println(jfMenu.getEmpleadosRegistrados());
            
            Empleado emp;
            String clase;
            
            for(int i=0; i<jfMenu.getEmpleadosRegistrados(); i++)
            {
                emp = jfMenu.getEmpleado(i);
                clase = emp.getClass().getSimpleName();
                
                if(clase.equals("Empleado"))
                {
                    pw.println("E");
                    pw.println(emp.getNumero());
                    pw.println(emp.getNombre());
                }

                if(clase.equals("Taller"))
                {
                    Taller t = (Taller)emp;
                    
                    pw.println("T");
                    pw.println(emp.getNumero());
                    pw.println(emp.getNombre());
                    pw.println(t.getPiezas());
                    pw.println(t.getPrecioUnitario());
                }
                
                if(clase.equals("Administrativo"))
                {
                    Administrativo a = (Administrativo)emp;
                    
                    pw.println("A");
                    pw.println(emp.getNumero());
                    pw.println(emp.getNombre());
                    pw.println(a.getDiasTrabajados());
                    pw.println(a.getSueldoDiario());
                }

                if(clase.equals("Ejecutivo"))
                {
                    Ejecutivo e = (Ejecutivo)emp;
                    
                    pw.println("EJ");
                    pw.println(emp.getNumero());
                    pw.println(emp.getNombre());
                    pw.println(e.getDiasTrabajados());
                    pw.println(e.getSueldoDiario());
                    pw.println(e.getBono());
                }

                if(clase.equals("Ventas"))
                {
                    Ventas v = (Ventas)emp;
                    
                    pw.println("V");
                    pw.println(emp.getNumero());
                    pw.println(emp.getNombre());
                    pw.println(v.getVentasTotales());
                    pw.println(v.getComision());
                }
            }
            
        } catch (IOException ex) {
            Logger.getLogger(JFrameRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally
        {
            if(pw != null)
                pw.close();
            
            if(fw != null)
                try {
                    fw.close();
            } catch (IOException ex) {
                Logger.getLogger(JFrameRegistro.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        this.dispose();
        jfMenu.getEtiqueta().setBackground(Color.pink);
        jfMenu.setVisible(true);
    }//GEN-LAST:event_jButRegresarActionPerformed

    private void jRBEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBEmpleadoActionPerformed
        // TODO add your handling code here:
        ocultar();
    }//GEN-LAST:event_jRBEmpleadoActionPerformed

    private void jRBTallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBTallerActionPerformed
        // TODO add your handling code here:
        ocultar();
        
        jLabPiezas.setVisible(true);
        jLabPrecio.setVisible(true);

        jTextPiezas.setVisible(true);
        jTextPrecio.setVisible(true);
    }//GEN-LAST:event_jRBTallerActionPerformed

    private void jRBVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBVentasActionPerformed
        // TODO add your handling code here:
        ocultar();
        
        jLabVentas.setVisible(true);
        jLabComision.setVisible(true);

        jTextVentas.setVisible(true);
        jTextComision.setVisible(true);
    }//GEN-LAST:event_jRBVentasActionPerformed

    private void jRBAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBAdminActionPerformed
        // TODO add your handling code here:
        ocultar();
        
        jLabDias.setVisible(true);
        jLabSueldo.setVisible(true);

        jTextDias.setVisible(true);
        jTextSueldo.setVisible(true);
    }//GEN-LAST:event_jRBAdminActionPerformed

    private void jRBEjecutivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBEjecutivoActionPerformed
        // TODO add your handling code here:
        ocultar();
        
        jLabDias.setVisible(true);
        jLabSueldo.setVisible(true);
        jLabBono.setVisible(true);
        
        jTextDias.setVisible(true);
        jTextSueldo.setVisible(true);
        jTextBono.setVisible(true);
    }//GEN-LAST:event_jRBEjecutivoActionPerformed

    private void jButAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatoriosActionPerformed
        // TODO add your handling code here:
        jTextNumero.setText(azar.nextInt(1000)+"");
        jTextNombre.setText(azar.nextNombreLegal());
        
        jTextPiezas.setText(azar.nextInt(100, 1000)+"");
        jTextPrecio.setText(azar.nextDouble(3, 8, .25)+"");
        
        jTextVentas.setText(azar.nextInt(5000, 70000, 1000)+"");
        jTextComision.setText(azar.nextDouble(2, 10, .5)+"");
        
        jTextDias.setText(azar.nextInt(7, 30)+"");
        jTextSueldo.setText(azar.nextInt(102, 500)+"");
        jTextBono.setText(azar.nextInt(2000, 20000, 1000)+"");
    }//GEN-LAST:event_jButAleatoriosActionPerformed

    private void jButGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButGrabarActionPerformed
        // TODO add your handling code here:
        int num = Integer.parseInt(jTextNumero.getText());
        String nom = jTextNombre.getText();
        
        if (jRBEmpleado.isSelected())
        {
            Empleado emp = new Empleado(num,nom);
            jfMenu.agregarEmpleado(emp);
        }
        
        if (jRBTaller.isSelected())
        {
            Taller tal = new Taller(num,nom,
                                    Integer.parseInt(jTextPiezas.getText()),
                                    Double.parseDouble(jTextPrecio.getText()));
            jfMenu.agregarEmpleado(tal);
        }
        
        if (jRBVentas.isSelected())
        {
            Ventas ven = new Ventas(num,nom,
                                    Double.parseDouble(jTextVentas.getText()),
                                    Double.parseDouble(jTextComision.getText()));
            
            jfMenu.agregarEmpleado(ven);
        }

        if (jRBAdmin.isSelected())
        {
            Administrativo adm = new Administrativo(num,nom,
                                                    Integer.parseInt(jTextDias.getText()),
                                                    Double.parseDouble(jTextSueldo.getText()));
            
            jfMenu.agregarEmpleado(adm);
        }
        
        if (jRBEjecutivo.isSelected())
        {
            Ejecutivo eje = new Ejecutivo(num,nom,
                                          Integer.parseInt(jTextDias.getText()),
                                          Double.parseDouble(jTextSueldo.getText()),
                                          Double.parseDouble(jTextBono.getText()));
            
            jfMenu.agregarEmpleado(eje);
        }
        
        jLabEmpReg.setText(jfMenu.getEmpleadosRegistrados()+"");
        jfMenu.ampliarArreglo();
        jLabEmpTot.setText("Capcidad:"+jfMenu.getTamaño()+"    Vacantes:"+(jfMenu.getTamaño()-jfMenu.getEmpleadosRegistrados()));
    }//GEN-LAST:event_jButGrabarActionPerformed

    private void jLabBonoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabBonoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabBonoMouseEntered

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:

        for (int i=1; i<=7; i++)
        {
            switch(azar.nextInt(5))
            {
                case 0: jRBEmpleado.setSelected(true); break;
                case 1: jRBTaller.setSelected(true); break;
                case 2: jRBVentas.setSelected(true); break;
                case 3: jRBAdmin.setSelected(true); break;
                case 4: jRBEjecutivo.setSelected(true); break;
            }

            jButAleatorios.doClick();
            jButGrabar.doClick();        
        }
    }//GEN-LAST:event_jLabel3MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameRegistro(new JFrameMenu()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButAleatorios;
    private javax.swing.JButton jButCancelar;
    private javax.swing.JButton jButGrabar;
    private javax.swing.JButton jButRegresar;
    private javax.swing.JLabel jLabBono;
    private javax.swing.JLabel jLabComision;
    private javax.swing.JLabel jLabDias;
    private javax.swing.JLabel jLabEmpReg;
    private javax.swing.JLabel jLabEmpTot;
    private javax.swing.JLabel jLabPiezas;
    private javax.swing.JLabel jLabPrecio;
    private javax.swing.JLabel jLabSueldo;
    private javax.swing.JLabel jLabVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRBAdmin;
    private javax.swing.JRadioButton jRBEjecutivo;
    private javax.swing.JRadioButton jRBEmpleado;
    private javax.swing.JRadioButton jRBTaller;
    private javax.swing.JRadioButton jRBVentas;
    private javax.swing.JTextField jTextBono;
    private javax.swing.JTextField jTextComision;
    private javax.swing.JTextField jTextDias;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextNumero;
    private javax.swing.JTextField jTextPiezas;
    private javax.swing.JTextField jTextPrecio;
    private javax.swing.JTextField jTextSueldo;
    private javax.swing.JTextField jTextVentas;
    // End of variables declaration//GEN-END:variables
}
