/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pa_2019_05_23_buscarnumero;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author alope
 */
public class JFrameTablero extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form JFrameTablero
     */
    MiBoton []tablero = new MiBoton[20];
    Random azar = new Random();
    int numeroABuscar, intentos;
    JFileChooser jfch = new JFileChooser();
    
    public JFrameTablero() {
        initComponents();
        
        setSize(550,550);
        iniciar();
    }

    public void iniciar()
    {
        int x = 30;
        int y = 50;
        
        MiBoton.setColor(2);
        
        for(int i=0; i<tablero.length; i++)
        {
            tablero[i] = new MiBoton(azar.nextInt(100));
            tablero[i].setLocation(x, y);

            x+=100;
            
            if((i+1)%5 ==0)
            {
                x = 30;
                y+=100;
            }
            
            tablero[i].addActionListener(this);
            
            add(tablero[i]);
        }
        
        intentos = 0;
        jLabIntentos.setText(intentos+"");
        
        numeroABuscar = tablero[azar.nextInt(tablero.length)].getNumero();
        jLabNumero.setText(numeroABuscar+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabNumero = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabIntentos = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuNuevo = new javax.swing.JMenuItem();
        jMenuAbrir = new javax.swing.JMenuItem();
        jMenuGuardar = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Número a buscar");

        jLabNumero.setBackground(new java.awt.Color(51, 255, 255));
        jLabNumero.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabNumero.setOpaque(true);

        jLabel3.setText("Intentos");

        jLabIntentos.setBackground(new java.awt.Color(255, 255, 0));
        jLabIntentos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabIntentos.setOpaque(true);

        jMenu1.setText("Archivo");

        jMenuNuevo.setText("Nuevo");
        jMenuNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNuevoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuNuevo);

        jMenuAbrir.setText("Abrir");
        jMenuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuAbrir);

        jMenuGuardar.setText("Guardar");
        jMenuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuGuardar);

        jMenuSalir.setText("Salir");
        jMenu1.add(jMenuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 246, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAbrirActionPerformed
        // TODO add your handling code here:
        if(jfch.showOpenDialog(jLabel1) != 0)
            return;
        
        FileInputStream fis = null;
        DataInputStream dis = null;
        
        try {
            fis = new FileInputStream(jfch.getSelectedFile());
            dis = new DataInputStream(fis);
            
            numeroABuscar = dis.readInt();
            intentos = dis.readInt();
            int colorBoton = dis.readInt();
            
            jLabNumero.setText(numeroABuscar+"");
            jLabIntentos.setText(intentos+"");
            
            for(int i=0; i<tablero.length; i++)
            {
                tablero[i].setNumero(dis.readInt());
                tablero[i].setEnabled(dis.readBoolean());
                tablero[i].setBackground(new Color(colorBoton));
                
                if(tablero[i].isEnabled())
                {
                    tablero[i].setText("");
                }
                else
                {
                    tablero[i].mostrar();
                }
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(JFrameTablero.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(JFrameTablero.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally
        {
            if(dis != null)
                try {
                    dis.close();
            } catch (IOException ex) {
                Logger.getLogger(JFrameTablero.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (fis != null)
                try {
                    fis.close();
            } catch (IOException ex) {
                Logger.getLogger(JFrameTablero.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuAbrirActionPerformed

    private void jMenuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGuardarActionPerformed
        // TODO add your handling code here:
        if(jfch.showSaveDialog(jLabel1) != 0)
            return;
        
        FileOutputStream fos = null;
        DataOutputStream dos = null;
        
        try {
            fos = new FileOutputStream(jfch.getSelectedFile());
            dos = new DataOutputStream(fos);
            
            dos.writeInt(numeroABuscar);
            dos.writeInt(intentos);
            dos.writeInt(tablero[0].getBackground().getRGB());
            
            for(MiBoton mb:tablero)
            {
                dos.writeInt(mb.getNumero());
                dos.writeBoolean(mb.isEnabled());
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(JFrameTablero.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(JFrameTablero.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally
        {
            try {
                if(dos != null)
                    dos.close();
                if(fos != null)
                    fos.close();
   } catch (IOException ex) {
                Logger.getLogger(JFrameTablero.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_jMenuGuardarActionPerformed

    private void jMenuNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNuevoActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<tablero.length; i++)
            this.remove(tablero[i]);
            
        iniciar();
        repaint();
    }//GEN-LAST:event_jMenuNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTablero().setVisible(true);
            }
        });
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        MiBoton boton = (MiBoton)e.getSource();
        
        boton.mostrar();
        boton.setEnabled(false);
        
        intentos++;
        jLabIntentos.setText(intentos+"");
        
        if(boton.getNumero() == numeroABuscar)
        {
            JOptionPane.showMessageDialog(rootPane, "Ya le atinó!!");
            
            for(MiBoton mb:tablero)
                mb.mostrar();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabIntentos;
    private javax.swing.JLabel jLabNumero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuAbrir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuGuardar;
    private javax.swing.JMenuItem jMenuNuevo;
    private javax.swing.JMenuItem jMenuSalir;
    // End of variables declaration//GEN-END:variables
}
