/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pa_2019_03_27_aplicacionnominaempleado;

import java.awt.Color;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aa523
 */
public class JFrameReporte extends javax.swing.JFrame {

    /**
     * Creates new form NeJFrame
     */
    JFrameMenu jfMenu;
    Empleado[] copia;
    
    DefaultTableModel modelo;
    public JFrameReporte(JFrameMenu jfm) {
        initComponents();
        
        jTableEmpleados.setShowGrid(true);
        jfMenu = jfm;
        jLabEmpReg.setText(jfMenu.getEmpleadosRegistrados()+"");
        
        copia = new Empleado[jfMenu.getEmpleadosRegistrados()];
        
        for(int i=0; i< copia.length; i++)
            copia[i] = jfMenu.getEmpleado(i);
        
        modelo= (DefaultTableModel)jTableEmpleados.getModel();
        modelo.setRowCount(copia.length);
        mostrar();
    }
    public void mostrar(){
        double total=0;
        for(int r=0; r< modelo.getRowCount(); r++){
                modelo.setValueAt(copia[r].getNumero(), r, 0);
                modelo.setValueAt(copia[r].getNombre(), r, 1);
                modelo.setValueAt(copia[r].sueldo(), r, 9);
                
                total += copia[r].sueldo();
        }
        jLabTotal.setText(total+"");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabEmpReg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpleados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabTotal = new javax.swing.JLabel();
        jButPorSueldo = new javax.swing.JButton();
        jButAleatorios = new javax.swing.JButton();
        jButOriginales = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jButRegresar.setText("Regresar");
        jButRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRegresarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Empleados registrados");

        jLabEmpReg.setBackground(new java.awt.Color(255, 204, 153));
        jLabEmpReg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabEmpReg.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabEmpReg.setOpaque(true);

        jTableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Nombre", "Piezas", "Precio unitario", "Ventas", "Comision", "Dias Trab", "Sueldo diario", "Bono", "Sueldo total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableEmpleados);
        if (jTableEmpleados.getColumnModel().getColumnCount() > 0) {
            jTableEmpleados.getColumnModel().getColumn(1).setPreferredWidth(150);
        }

        jLabel1.setText("total");

        jLabTotal.setBackground(new java.awt.Color(102, 102, 255));
        jLabTotal.setOpaque(true);
        jLabTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabTotalMouseEntered(evt);
            }
        });

        jButPorSueldo.setText("Por sueldo");
        jButPorSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButPorSueldoActionPerformed(evt);
            }
        });

        jButAleatorios.setText("Aleatorios");

        jButOriginales.setText("Datos originales");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(392, 392, 392)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabEmpReg, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButRegresar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButPorSueldo)
                                .addGap(18, 18, 18)
                                .addComponent(jButAleatorios)
                                .addGap(34, 34, 34)
                                .addComponent(jButOriginales)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 342, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButRegresar)
                    .addComponent(jLabel2)
                    .addComponent(jLabEmpReg, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButPorSueldo)
                        .addComponent(jButAleatorios)
                        .addComponent(jButOriginales))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRegresarActionPerformed
        this.dispose();
        jfMenu.getEtiqueta().setBackground(Color.ORANGE);
        jfMenu.setVisible(true);
    }//GEN-LAST:event_jButRegresarActionPerformed

    private void jButPorSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButPorSueldoActionPerformed
        
    }//GEN-LAST:event_jButPorSueldoActionPerformed

    private void jLabTotalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabTotalMouseEntered
  

    }//GEN-LAST:event_jLabTotalMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameReporte(new JFrameMenu()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAleatorios;
    private javax.swing.JButton jButOriginales;
    private javax.swing.JButton jButPorSueldo;
    private javax.swing.JButton jButRegresar;
    private javax.swing.JLabel jLabEmpReg;
    private javax.swing.JLabel jLabTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmpleados;
    // End of variables declaration//GEN-END:variables
}
