/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pa_2019_03_27_aplicacionnominaempleado;

import java.awt.Color;

/**
 *
 * @author aa523
 */
public class JFrameRegistro extends javax.swing.JFrame {

    /**
     * Creates new form JFrameRegistro
     */
    JFrameMenu jfMenu;
    MiRandom azar = new MiRandom();
    public JFrameRegistro(JFrameMenu jfm) {
        initComponents();
       
        jfMenu = jfm;
        jRBEmpleados.setSelected(true);
        ocultar();
        
        jLabEmpReg.setText(jfMenu.getEmpleadosRegistrados()+"");
    }
    public void ocultar(){
        jLabPiezas.setVisible(false);
        jLabPrecio.setVisible(false);
        jLabVentas.setVisible(false);
        jLabComision.setVisible(false);
        jLabDiasTrab.setVisible(false);
        jLabSueldoD.setVisible(false);
        jLabBono.setVisible(false);
        
        jTextPiezas.setVisible(false);
        jTextPrecio.setVisible(false);
        jTextVentas.setVisible(false);
        jTextComision.setVisible(false);
        jTextDias.setVisible(false);
        jTextSueldoD.setVisible(false);
        jTextBono.setVisible(false);  
        
                
        jTextNumero.setText("");
        jTextNombre.setText("");
        jTextPiezas.setText("");
        jTextPrecio.setText("");
        jTextVentas.setText("");
        jTextComision.setText("");
        jTextDias.setText("");
        jTextSueldoD.setText("");
        jTextBono.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabEmpReg = new javax.swing.JLabel();
        jRBEmpleados = new javax.swing.JRadioButton();
        jRBTaller = new javax.swing.JRadioButton();
        jRBVentas = new javax.swing.JRadioButton();
        jRBAdministrativo = new javax.swing.JRadioButton();
        jRBEjecutivo = new javax.swing.JRadioButton();
        jButAleatorios = new javax.swing.JButton();
        jButGrabar = new javax.swing.JButton();
        jButCancelar = new javax.swing.JButton();
        jLabNumero = new javax.swing.JLabel();
        jTextNumero = new javax.swing.JTextField();
        jTextNombre = new javax.swing.JTextField();
        jLabNombre = new javax.swing.JLabel();
        jTextPiezas = new javax.swing.JTextField();
        jLabPiezas = new javax.swing.JLabel();
        jTextPrecio = new javax.swing.JTextField();
        jLabPrecio = new javax.swing.JLabel();
        jTextVentas = new javax.swing.JTextField();
        jLabVentas = new javax.swing.JLabel();
        jTextComision = new javax.swing.JTextField();
        jLabComision = new javax.swing.JLabel();
        jTextDias = new javax.swing.JTextField();
        jLabDiasTrab = new javax.swing.JLabel();
        jTextSueldoD = new javax.swing.JTextField();
        jLabSueldoD = new javax.swing.JLabel();
        jLabBono = new javax.swing.JLabel();
        jTextBono = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 204));
        jLabel1.setText("Registro de empleados");

        jButRegresar.setText("Regresar");
        jButRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRegresarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Empleados registrados");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabEmpRegMouseEntered(evt);
            }
        });

        jLabEmpReg.setBackground(new java.awt.Color(255, 204, 153));
        jLabEmpReg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabEmpReg.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabEmpReg.setOpaque(true);

        buttonGroup1.add(jRBEmpleados);
        jRBEmpleados.setText("Empleado");
        jRBEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBEmpleadosActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBTaller);
        jRBTaller.setText("Taller");
        jRBTaller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBTallerActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBVentas);
        jRBVentas.setText("Ventas");
        jRBVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBVentasActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBAdministrativo);
        jRBAdministrativo.setText("Administrativo");
        jRBAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBAdministrativoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBEjecutivo);
        jRBEjecutivo.setText("Ejecutivo");
        jRBEjecutivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBEjecutivoActionPerformed(evt);
            }
        });

        jButAleatorios.setText("Aleatorios");
        jButAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatoriosActionPerformed(evt);
            }
        });

        jButGrabar.setText("Grabar");
        jButGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButGrabarActionPerformed(evt);
            }
        });

        jButCancelar.setText("Cancelar");

        jLabNumero.setText("Numero");
        jLabNumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabNumeroMouseEntered(evt);
            }
        });

        jLabNombre.setText("Nombre");

        jLabPiezas.setText("Piezas");

        jLabPrecio.setText("Precio Unitario");

        jLabVentas.setText("Ventas$");

        jLabComision.setText("%Comision");

        jLabDiasTrab.setText("Dias Trabajados");

        jLabSueldoD.setText("Sueldo diario");

        jLabBono.setText("Bono$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jButRegresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButAleatorios)
                                .addGap(31, 31, 31)
                                .addComponent(jButGrabar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRBEmpleados)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRBTaller))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabNumero)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabNombre)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRBVentas)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRBAdministrativo)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRBEjecutivo))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabDiasTrab)
                                .addGap(18, 18, 18)
                                .addComponent(jTextDias, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabSueldoD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextSueldoD, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabBono)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextBono, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabPiezas)
                                        .addGap(26, 26, 26)
                                        .addComponent(jTextPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabVentas)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabComision)
                                    .addComponent(jLabPrecio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextComision, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabEmpReg, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jButCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButRegresar))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBEmpleados)
                    .addComponent(jRBTaller)
                    .addComponent(jRBVentas)
                    .addComponent(jRBAdministrativo)
                    .addComponent(jRBEjecutivo))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabNumero)
                    .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabNombre)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabPiezas)
                    .addComponent(jTextPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabPrecio)
                    .addComponent(jTextPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabVentas)
                    .addComponent(jTextVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabComision)
                    .addComponent(jTextComision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabDiasTrab)
                    .addComponent(jTextDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabSueldoD)
                    .addComponent(jTextSueldoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabBono)
                    .addComponent(jTextBono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButAleatorios)
                    .addComponent(jButGrabar)
                    .addComponent(jButCancelar))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabEmpReg, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRegresarActionPerformed
        this.dispose();
        jfMenu.getEtiqueta().setBackground(Color.WHITE);
        jfMenu.setVisible(true);
    }//GEN-LAST:event_jButRegresarActionPerformed

    private void jRBEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBEmpleadosActionPerformed
        ocultar();
    }//GEN-LAST:event_jRBEmpleadosActionPerformed

    private void jRBTallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBTallerActionPerformed
        ocultar();
        
        jLabPiezas.setVisible(true);
        jLabPrecio.setVisible(true);
        jTextPiezas.setVisible(true);
        jTextPrecio.setVisible(true);
    }//GEN-LAST:event_jRBTallerActionPerformed

    private void jRBVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBVentasActionPerformed
        ocultar();
        jLabVentas.setVisible(true);
        jLabComision.setVisible(true);
        jTextVentas.setVisible(true);
        jTextComision.setVisible(true);
    }//GEN-LAST:event_jRBVentasActionPerformed

    private void jRBAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBAdministrativoActionPerformed
        ocultar();
        jLabDiasTrab.setVisible(true);
        jLabSueldoD.setVisible(true);
        
        jTextDias.setVisible(true);
        jTextSueldoD.setVisible(true);
    }//GEN-LAST:event_jRBAdministrativoActionPerformed

    private void jRBEjecutivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBEjecutivoActionPerformed
        ocultar();
        jLabDiasTrab.setVisible(true);
        jLabSueldoD.setVisible(true);
        jLabBono.setVisible(true);
        
        jTextDias.setVisible(true);
        jTextSueldoD.setVisible(true);        
        jTextBono.setVisible(true);
    }//GEN-LAST:event_jRBEjecutivoActionPerformed

    private void jButAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatoriosActionPerformed
        MiRandom azar = new MiRandom();
        jTextNumero.setText(azar.nextInt(100)+"");
        jTextNombre.setText(azar.nextNombreLegal()+"");
        
        jTextPiezas.setText(azar.nextInt(100, 1000)+"");
        jTextPrecio.setText(azar.nextDouble(3, 8, .25)+"");
        
        jTextVentas.setText(azar.nextInt(5000, 70000, 1000)+"");
        jTextComision.setText(azar.nextDouble(2,10,.5)+"");
        
        jTextDias.setText(azar.nextInt(7,30)+"");
        jTextSueldoD.setText(azar.nextInt(102, 500)+"");
        jTextBono.setText(azar.nextInt(2000,20000,1000)+"");

                
    }//GEN-LAST:event_jButAleatoriosActionPerformed

    private void jButGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButGrabarActionPerformed
        int num = Integer.parseInt(jTextNumero.getText());
        String nom = jTextNombre.getText();
        
        if(jRBEmpleados.isSelected()){
            Empleado emp = new Empleado(num,nom);
            jfMenu.agregarEmpleado(emp);
        }
        if(jRBTaller.isSelected()){
            Taller tal = new Taller(num, nom, Integer.parseInt(jTextPiezas.getText()), Double.parseDouble(jTextPrecio.getText()));
            jfMenu.agregarEmpleado(tal);
        }
        if(jRBVentas.isSelected()){
            Ventas ven = new Ventas(num,nom,Double.parseDouble(jTextVentas.getText()),Double.parseDouble(jTextComision.getText()));
            jfMenu.agregarEmpleado(ven);
        }
        if(jRBAdministrativo.isSelected()){
            Administrativo adm = new Administrativo(num, nom, Integer.parseInt(jTextDias.getText()), Double.parseDouble(jTextPrecio.getText()));
            jfMenu.agregarEmpleado(adm);
        }
        if(jRBEjecutivo.isSelected()){
            Ejecutivo eje = new Ejecutivo(num, nom, Integer.parseInt(jTextDias.getText()), Double.parseDouble(jTextPrecio.getText()), Double.parseDouble(jTextBono.getText()));
            jfMenu.agregarEmpleado(eje);
        }
        
        jLabEmpReg.setText(jfMenu.getEmpleadosRegistrados()+"");
    }//GEN-LAST:event_jButGrabarActionPerformed

    private void jLabEmpRegMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabEmpRegMouseEntered
 
    }//GEN-LAST:event_jLabEmpRegMouseEntered

    private void jLabNumeroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabNumeroMouseEntered
        for(int i=0; i < 7;i++)
        {
        switch(azar.nextInt(5)){
            case 0: jRBEmpleados.setSelected(true);break;
            case 1: jRBTaller.setSelected(true);break;
            case 2: jRBVentas.setSelected(true);break;
            case 3: jRBAdministrativo.setSelected(true);break;
            case 4: jRBEjecutivo.setSelected(true);break;
        }
        jButAleatorios.doClick();
        jButGrabar.doClick();       
        }
    }//GEN-LAST:event_jLabNumeroMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameRegistro(new JFrameMenu()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButAleatorios;
    private javax.swing.JButton jButCancelar;
    private javax.swing.JButton jButGrabar;
    private javax.swing.JButton jButRegresar;
    private javax.swing.JLabel jLabBono;
    private javax.swing.JLabel jLabComision;
    private javax.swing.JLabel jLabDiasTrab;
    private javax.swing.JLabel jLabEmpReg;
    private javax.swing.JLabel jLabNombre;
    private javax.swing.JLabel jLabNumero;
    private javax.swing.JLabel jLabPiezas;
    private javax.swing.JLabel jLabPrecio;
    private javax.swing.JLabel jLabSueldoD;
    private javax.swing.JLabel jLabVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRBAdministrativo;
    private javax.swing.JRadioButton jRBEjecutivo;
    private javax.swing.JRadioButton jRBEmpleados;
    private javax.swing.JRadioButton jRBTaller;
    private javax.swing.JRadioButton jRBVentas;
    private javax.swing.JTextField jTextBono;
    private javax.swing.JTextField jTextComision;
    private javax.swing.JTextField jTextDias;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextNumero;
    private javax.swing.JTextField jTextPiezas;
    private javax.swing.JTextField jTextPrecio;
    private javax.swing.JTextField jTextSueldoD;
    private javax.swing.JTextField jTextVentas;
    // End of variables declaration//GEN-END:variables
}
