/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pa_2019_03_06_matrices;

import java.util.Random;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aa523
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    
    private DefaultTableModel modeloA, modeloB, modeloC;
    Matriz A, B, C; 
    public JFrame() {
        initComponents();
        
        modeloA = (DefaultTableModel)jTableMatrizA.getModel();
        modeloB = (DefaultTableModel)jTableMatrizB.getModel();
        modeloC = (DefaultTableModel)jTableMatrizC.getModel();
        
        jTableMatrizA.setShowGrid(true);
        jTableMatrizB.setShowGrid(true);
        jTableMatrizC.setShowGrid(true);
        
        jSpinRenA.setValue(1);
        jSpinColA.setValue(1);
        jSpinRenB.setValue(1);
        jSpinColB.setValue(1);
    }
    
    public void crearA()
    {
        A = new Matriz(modeloA.getRowCount(),modeloA.getColumnCount());
        
        int r, c;
        for(r = 0; r<A.getRenglones(); r++)
            for(c = 0; c<A.getColumnas(); c++)
                A.setValor(Double.parseDouble(modeloA.getValueAt(r, c)+""), r, c);       
    }

    public void crearB() 
    {
        B = new Matriz(modeloB.getRowCount(),modeloB.getColumnCount());
        
        int r, c;
        for(r = 0; r<B.getRenglones(); r++)
            for(c = 0; c<B.getColumnas(); c++)
                B.setValor(Double.parseDouble(modeloB.getValueAt(r, c)+""), r, c);
    }
    
    public void mostrarC() 
    {
        modeloC.setRowCount(C.getRenglones());
        modeloC.setColumnCount(C.getColumnas());

        jLabelRen.setText(C.getRenglones()+"");
        jLabelCol.setText(C.getColumnas()+"");
        
        int r, c;
        for(r = 0; r<C.getRenglones(); r++)
            for(c = 0; c<C.getColumnas(); c++)
                modeloC.setValueAt(C.getValor(r, c), r, c);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMatrizB = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableMatrizA = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableMatrizC = new javax.swing.JTable();
        jButSuma = new javax.swing.JButton();
        jButRes = new javax.swing.JButton();
        jButPor = new javax.swing.JButton();
        jTextEsc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSpinRenA = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSpinColA = new javax.swing.JSpinner();
        jSpinColB = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jSpinRenB = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelRen = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabelCol = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButAlea = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableMatrizB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableMatrizB);

        jTableMatrizA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTableMatrizA);

        jTableMatrizC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jTableMatrizC);

        jButSuma.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButSuma.setText("+");
        jButSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButSumaActionPerformed(evt);
            }
        });

        jButRes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButRes.setText("-");

        jButPor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButPor.setText("*");
        jButPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButPorActionPerformed(evt);
            }
        });

        jTextEsc.setBackground(new java.awt.Color(0, 204, 204));
        jTextEsc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Escalar");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("=");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Renglones");

        jSpinRenA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jSpinRenA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinRenAStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("*");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Columnas");

        jSpinColA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jSpinColA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinColAStateChanged(evt);
            }
        });

        jSpinColB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jSpinColB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinColBStateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Renglones");

        jSpinRenB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jSpinRenB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinRenBStateChanged(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("*");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Columnas");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Renglones");

        jLabelRen.setBackground(new java.awt.Color(0, 204, 204));
        jLabelRen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelRen.setOpaque(true);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("*");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Columnas");

        jLabelCol.setBackground(new java.awt.Color(0, 204, 204));
        jLabelCol.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCol.setOpaque(true);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 0, 153));
        jLabel14.setText("Matriz B");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 0, 153));
        jLabel15.setText("Matriz C");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 0, 153));
        jLabel16.setText("Matriz A");

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox1.setText("Sincronizar");

        jButAlea.setText("Aleatorios");
        jButAlea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextEsc)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jButPor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jButSuma, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jButRes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 10, Short.MAX_VALUE)))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSpinRenA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jSpinColA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButAlea, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(28, 28, 28)
                                .addComponent(jSpinRenB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinColB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelRen, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12)))
                                .addGap(33, 33, 33)
                                .addComponent(jLabelCol, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(513, 513, 513)
                        .addComponent(jLabel14)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelCol, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jSpinRenA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jSpinColA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(jSpinRenB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jSpinColB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(jLabelRen, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(25, 25, 25)
                        .addComponent(jCheckBox1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jButSuma)
                                .addGap(18, 18, 18)
                                .addComponent(jButRes)
                                .addGap(18, 18, 18)
                                .addComponent(jButPor)
                                .addGap(18, 18, 18)
                                .addComponent(jTextEsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)))
                        .addGap(8, 8, 8)
                        .addComponent(jButAlea)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(209, 209, 209))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButPorActionPerformed
        // TODO add your handling code here:
        crearA();
        
        if(jTextEsc.getText().equals(""))
        {
            crearB();
            C = A.multiplicacion(B);       
        }
        else 
        {
            C = A.Multiplicacion(Double.parseDouble(jTextEsc.getText()));
        }
        mostrarC();
    }//GEN-LAST:event_jButPorActionPerformed

    private void jSpinRenAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinRenAStateChanged
        // TODO add your handling code here:
        
        int ren = (int)jSpinRenA.getValue();
        
        modeloA.setRowCount(ren);
        
        if(jCheckBox1.isSelected())
            jSpinRenB.setValue(ren);
        
    }//GEN-LAST:event_jSpinRenAStateChanged

    private void jSpinColAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinColAStateChanged
        // TODO add your handling code here:
        
        int col = (int)jSpinColA.getValue();
        
        modeloA.setColumnCount(col);       
        
        if(jCheckBox1.isSelected())
            jSpinColB.setValue(col);
        
    }//GEN-LAST:event_jSpinColAStateChanged

    private void jSpinRenBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinRenBStateChanged
        // TODO add your handling code here:
        
        int ren = (int)jSpinRenB.getValue();
        
        modeloB.setRowCount(ren);  
        
        if(jCheckBox1.isSelected())
            jSpinRenA.setValue(ren);
        
    }//GEN-LAST:event_jSpinRenBStateChanged

    private void jSpinColBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinColBStateChanged
        // TODO add your handling code here:
        
        int col = (int)jSpinColB.getValue();
        
        modeloB.setColumnCount(col);        
        
        if(jCheckBox1.isSelected())
            jSpinColA.setValue(col);
    }//GEN-LAST:event_jSpinColBStateChanged

    private void jButAleaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleaActionPerformed
        // TODO add your handling code here:
        
        Random azar = new Random();
        
        int r, c;
        
        for(r = 0; r<modeloA.getRowCount(); r++){
            for(c = 0; c<modeloA.getColumnCount(); c++){
                modeloA.setValueAt(azar.nextInt(100), r, c);
            }
        }
        
        for(r = 0; r<modeloB.getRowCount(); r++){
            for(c = 0; c<modeloB.getColumnCount(); c++){
                modeloB.setValueAt(azar.nextInt(100), r, c);
            }
        }
    }//GEN-LAST:event_jButAleaActionPerformed

    private void jButSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButSumaActionPerformed
        // TODO add your handling code here:
       
        crearA();
        crearB();
        
        C = A.suma(B);
        
        mostrarC();
    }//GEN-LAST:event_jButSumaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAlea;
    private javax.swing.JButton jButPor;
    private javax.swing.JButton jButRes;
    private javax.swing.JButton jButSuma;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCol;
    private javax.swing.JLabel jLabelRen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinColA;
    private javax.swing.JSpinner jSpinColB;
    private javax.swing.JSpinner jSpinRenA;
    private javax.swing.JSpinner jSpinRenB;
    private javax.swing.JTable jTableMatrizA;
    private javax.swing.JTable jTableMatrizB;
    private javax.swing.JTable jTableMatrizC;
    private javax.swing.JTextField jTextEsc;
    // End of variables declaration//GEN-END:variables
}
