/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pa_2019_02_18_aplicacionnomina;

import java.text.DecimalFormat;
import java.util.Random;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aa527
 */
public class JFrameNomina extends javax.swing.JFrame {

    /**
     * Creates new form JFrameNomina
     */
    
    Empleado [] nomina = new Empleado[10];
    
    public JFrameNomina() {
        initComponents();
        
       DefaultTableModel modelo = (DefaultTableModel)jTableNomina.getModel();
       modelo.setRowCount(nomina.length);
       
       for(int i=0; i<nomina.length; i++)
           nomina [i] = new Empleado();
       mostrar();
        
    }
    
    public void mostrar(){
        
        DecimalFormat d = new DecimalFormat("#,###,##0.00");
        double total = 0;
        
        for(int r=0; r<nomina.length; r++){
            jTableNomina.setValueAt(nomina[r].getNombre(), r, 0);
            jTableNomina.setValueAt(nomina[r].getDiasTrabajados(), r, 1);
            jTableNomina.setValueAt(d.format(nomina[r].getSueldoDiario()), r, 2);
            jTableNomina.setValueAt(nomina[r].getHorasExtras(), r, 3);
            jTableNomina.setValueAt(nomina[r].getPorcentajeImpuesto(), r, 4);
            
            
            jTableNomina.setValueAt(d.format(nomina[r].importeHorasExtra()), r, 5);
            jTableNomina.setValueAt(d.format(nomina[r].importeImpuesto()), r, 6);
            jTableNomina.setValueAt(d.format(nomina[r].sueldo()), r, 7);
            
            total+=nomina[r].sueldo();
        }
        
        jLabTotal.setText(d.format(total)+"");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNomina = new javax.swing.JTable();
        jTextNombre = new javax.swing.JTextField();
        jTextSueldo = new javax.swing.JTextField();
        jTextDias = new javax.swing.JTextField();
        jTextHoras = new javax.swing.JTextField();
        jTextImpuesto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButGrabar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSpinPosicion = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabTotal = new javax.swing.JLabel();
        jButAleatorios = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButMayMen = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabMayor = new javax.swing.JLabel();
        jLabMenor = new javax.swing.JLabel();
        jButSueldo = new javax.swing.JButton();
        jButAlfabeto = new javax.swing.JButton();
        jButEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTableNomina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Empleado", "Dias Trab", "Sueldo Dia", "Hor Extras", "% Impuesto", "% Hor ext", "$ Impuesto", "$ Sueldo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableNomina);
        if (jTableNomina.getColumnModel().getColumnCount() > 0) {
            jTableNomina.getColumnModel().getColumn(0).setPreferredWidth(150);
        }

        jTextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreActionPerformed(evt);
            }
        });

        jTextSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSueldoActionPerformed(evt);
            }
        });

        jTextDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDiasActionPerformed(evt);
            }
        });

        jTextHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextHorasActionPerformed(evt);
            }
        });

        jTextImpuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextImpuestoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Dias Trab");

        jLabel3.setText("Sueldo Dia");

        jLabel4.setText("Hor Extras");

        jLabel5.setText("%I mpuesto");

        jButGrabar.setText("Grabar");
        jButGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButGrabarActionPerformed(evt);
            }
        });

        jLabel6.setText("Posición");

        jSpinPosicion.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        jSpinPosicion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinPosicionStateChanged(evt);
            }
        });

        jLabel7.setText("Total");

        jLabTotal.setBackground(new java.awt.Color(153, 204, 255));
        jLabTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabTotal.setOpaque(true);

        jButAleatorios.setText("Aleatorios");
        jButAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatoriosActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Incremento Autom.");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jButMayMen.setText("Mayor y menor");
        jButMayMen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButMayMenActionPerformed(evt);
            }
        });

        jLabel8.setText("Mayor");

        jLabel9.setText("Menor");

        jLabMayor.setBackground(new java.awt.Color(255, 102, 102));
        jLabMayor.setOpaque(true);

        jLabMenor.setBackground(new java.awt.Color(255, 102, 102));
        jLabMenor.setOpaque(true);

        jButSueldo.setText("Por sueldo");
        jButSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButSueldoActionPerformed(evt);
            }
        });

        jButAlfabeto.setText("Alfabeto");
        jButAlfabeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAlfabetoActionPerformed(evt);
            }
        });

        jButEditar.setText("Editar");
        jButEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTextDias, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTextSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTextHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTextImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jButAleatorios)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSpinPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButSueldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButMayMen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButAlfabeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabMenor, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(jLabMayor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButAleatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jCheckBox1)
                        .addComponent(jButMayMen)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButSueldo)
                    .addComponent(jButAlfabeto)
                    .addComponent(jButEditar))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreActionPerformed

    private void jTextSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSueldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSueldoActionPerformed

    private void jTextDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDiasActionPerformed

    private void jTextHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextHorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextHorasActionPerformed

    private void jTextImpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextImpuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextImpuestoActionPerformed

    private void jButAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatoriosActionPerformed
        // TODO add your handling code here:
        Random azar = new Random();
        jTextNombre.setText(Nombre.nextNombreLegal());
        jTextDias.setText(5+azar.nextInt(11)+"");
        jTextSueldo.setText(102.6+azar.nextInt(500)+"");
        jTextHoras.setText(azar.nextInt(20)+"");
        jTextImpuesto.setText(azar.nextInt(15)+"");
    }//GEN-LAST:event_jButAleatoriosActionPerformed

    private void jButGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButGrabarActionPerformed
        // TODO add your handling code here:
        Empleado x = new Empleado();
        x.setNombre(jTextNombre.getText());
        x.setDiasTrabajados(Integer.parseInt((jTextDias.getText())));
        x.setSueldoDiario(Double.parseDouble(jTextSueldo.getText()));
        x.setHorasExtras((Integer.parseInt(jTextHoras.getText())));
        x.setPorcentajeImpuesto(Double.parseDouble(jTextImpuesto.getText()));
        
        
        int posicion = (int)jSpinPosicion.getValue()-1;
        nomina[posicion] = x;
        
        mostrar();
        
        
        if(jCheckBox1.isSelected())
            if(posicion == nomina.length-1)
                jSpinPosicion.setValue(1);
            else
                jSpinPosicion.setValue(posicion+2);
        
    }//GEN-LAST:event_jButGrabarActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButMayMenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButMayMenActionPerformed
        // TODO add your handling code here:
        Empleado mayor = nomina[0];
        Empleado menor = nomina[0];
        for(int r=1; r<nomina.length; r++){
            if(nomina[r].sueldo()>mayor.sueldo())
                mayor = nomina[r];
            if(nomina[r].sueldo()<menor.sueldo())
                menor = nomina[r];
        }
        
        jLabMayor.setText(mayor.getNombre());
        jLabMenor.setText(menor.getNombre());
    }//GEN-LAST:event_jButMayMenActionPerformed

    private void jButSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButSueldoActionPerformed
        // TODO add your handling code here:
        for(int i =0; i<nomina.length-1; i++)
            for(int j=i+1; j<nomina.length; j++)
                if(nomina[i].sueldo()<nomina[j].sueldo()){
                    Empleado aux = nomina[i];
                    nomina[i] = nomina[j];
                    nomina[j] = aux;
                }
        mostrar();
    }//GEN-LAST:event_jButSueldoActionPerformed

    private void jButAlfabetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAlfabetoActionPerformed
        // TODO add your handling code here:
        for(int i =0; i<nomina.length-1; i++)
            for(int j=i+1; j<nomina.length; j++)
                if(nomina[i].getNombre().compareTo(nomina[j].getNombre()) > 0){
                    Empleado aux = nomina[i];
                    nomina[i] = nomina[j];
                    nomina[j] = aux;
                }
        mostrar();
    }//GEN-LAST:event_jButAlfabetoActionPerformed

    private void jButEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEditarActionPerformed
        // TODO add your handling code here:
         int posicion = (int)jSpinPosicion.getValue()-1;
         Empleado x = nomina[posicion];
         
         jTextNombre.setText(x.getNombre());
         jTextDias.setText(x.getDiasTrabajados()+"");
         jTextSueldo.setText(x.getSueldoDiario()+"");
         jTextHoras.setText(x.getHorasExtras()+"");
         jTextImpuesto.setText(x.getPorcentajeImpuesto()+"");
    }//GEN-LAST:event_jButEditarActionPerformed

    private void jSpinPosicionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinPosicionStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinPosicionStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameNomina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAleatorios;
    private javax.swing.JButton jButAlfabeto;
    private javax.swing.JButton jButEditar;
    private javax.swing.JButton jButGrabar;
    private javax.swing.JButton jButMayMen;
    private javax.swing.JButton jButSueldo;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabMayor;
    private javax.swing.JLabel jLabMenor;
    private javax.swing.JLabel jLabTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinPosicion;
    private javax.swing.JTable jTableNomina;
    private javax.swing.JTextField jTextDias;
    private javax.swing.JTextField jTextHoras;
    private javax.swing.JTextField jTextImpuesto;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextSueldo;
    // End of variables declaration//GEN-END:variables
}
