package pa_18131209_proyecto_03;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author José Misael Adame Sandoval
 */
public class PA_18131209_Frame_03 extends javax.swing.JFrame {

    // Obtener el modelo de la tabla
    DefaultTableModel modelo;
    
    // Declaracion de variables
    Pelicula [] filmes = new Pelicula[4];
    Pelicula [] dibujos = new Pelicula[filmes.length];
    
    FilmeA1 lv;
    FilmeA2 dead;
    FilmeT1 rec;
    FilmeT2 it;
    
    public PA_18131209_Frame_03() {
        initComponents();
        modelo = (DefaultTableModel)jTablePeliculas.getModel();
        
        filmes[0] = lv ;
        filmes[1] = dead;
        filmes[2] = rec;
        filmes[3] = it;
        
        // Deshabilitar botones
        this.deshabilitar();
        
        
    }
    
    public Pelicula[] getInformacion() 
    {
        return filmes;
    }
    
    public void deshabilitar() 
    {
        jButMostrar.setEnabled(false);
        jButDesfile.setEnabled(false);
    }
    
    public void hablitar() 
    {
        jButMostrar.setEnabled(true);
        jButDesfile.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePeliculas = new javax.swing.JTable();
        jButGrabar = new javax.swing.JButton();
        jButMostrar = new javax.swing.JButton();
        jButEjemplo = new javax.swing.JButton();
        jButDiagrama = new javax.swing.JButton();
        jButDesfile = new javax.swing.JButton();
        jPanelDibujo = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaInfo = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jSpinnerPosicion = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pa_18131209_proyecto_03/AsignacionProyecto.jpg"))); // NOI18N

        jTablePeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Año", "Director"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePeliculas);
        if (jTablePeliculas.getColumnModel().getColumnCount() > 0) {
            jTablePeliculas.getColumnModel().getColumn(0).setResizable(false);
            jTablePeliculas.getColumnModel().getColumn(2).setResizable(false);
        }

        jButGrabar.setText("Grabar");
        jButGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButGrabarActionPerformed(evt);
            }
        });

        jButMostrar.setText("Mostrar");
        jButMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButMostrarActionPerformed(evt);
            }
        });

        jButEjemplo.setText("Ejemplo");
        jButEjemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEjemploActionPerformed(evt);
            }
        });

        jButDiagrama.setText("Diagrama");
        jButDiagrama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDiagramaActionPerformed(evt);
            }
        });

        jButDesfile.setText("Desfile");
        jButDesfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDesfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDibujoLayout = new javax.swing.GroupLayout(jPanelDibujo);
        jPanelDibujo.setLayout(jPanelDibujoLayout);
        jPanelDibujoLayout.setHorizontalGroup(
            jPanelDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
        );
        jPanelDibujoLayout.setVerticalGroup(
            jPanelDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        jTextAreaInfo.setEditable(false);
        jTextAreaInfo.setColumns(20);
        jTextAreaInfo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextAreaInfo.setRows(5);
        jScrollPane3.setViewportView(jTextAreaInfo);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pa_18131209_proyecto_03/Informacion.jpg"))); // NOI18N

        jSpinnerPosicion.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));

        jLabel3.setText("Posición:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButMostrar)
                                .addGap(26, 26, 26)
                                .addComponent(jButGrabar)
                                .addGap(18, 18, 18)
                                .addComponent(jButEjemplo)
                                .addGap(18, 18, 18)
                                .addComponent(jButDiagrama)
                                .addGap(18, 18, 18)
                                .addComponent(jButDesfile)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)))
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButMostrar)
                    .addComponent(jButGrabar)
                    .addComponent(jButEjemplo)
                    .addComponent(jButDiagrama)
                    .addComponent(jButDesfile)
                    .addComponent(jSpinnerPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelDibujo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButGrabarActionPerformed
        // TODO add your handling code here:
        
        FilmeA1 pel1 = new FilmeA1( 
                      (String)modelo.getValueAt(0, 0),
                      (int)modelo.getValueAt(0, 1),
                      (String)modelo.getValueAt(0, 2),
                      "Deadpool", "Estados Unidos");
            
        FilmeA2 pel2 = new FilmeA2( 
                      (String)modelo.getValueAt(1, 0),
                      (int)modelo.getValueAt(1, 1),
                      (String)modelo.getValueAt(1, 2),
                      "Linterna Verde", "DC");
                                   
        FilmeT1 pel3 = new FilmeT1( 
                      (String)modelo.getValueAt(2, 0),
                      (int)modelo.getValueAt(2, 1),
                      (String)modelo.getValueAt(2, 2),
                      "REC", "Filmax");
                                   
        FilmeT2 pel4 = new FilmeT2( 
                      (String)modelo.getValueAt(3, 0),
                      (int)modelo.getValueAt(3, 1),
                      (String)modelo.getValueAt(3, 2),
                      "Pennywise", 700381748);
                
        filmes[0] = pel1;
        filmes[1] = pel2;
        filmes[2] = pel3;
        filmes[3] = pel4;

        for(int  i = 0; i <filmes.length-1; i++)
        {
            for(int j = i+1; j<filmes.length; j++)
            {
                if(filmes[i].getNombre().length() < filmes[j].getNombre().length())
                {
                    Pelicula aux = filmes[i];
                    filmes[i] = filmes[j];
                    filmes[j] = aux;
                }
            }
        }
        
        this.hablitar();
        
    }//GEN-LAST:event_jButGrabarActionPerformed

    private void jButEjemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEjemploActionPerformed
        
        // Se agregan los ejemplos en la tabla (jTablePeliculas)
        modelo.setValueAt("Deadpool", 0, 0);
        modelo.setValueAt(2016, 0, 1);
        modelo.setValueAt("Tim Miller", 0, 2); 
        
        modelo.setValueAt("Linterna Verde", 1, 0);
        modelo.setValueAt(2011, 1, 1);
        modelo.setValueAt("Martin Campbell", 1, 2);
        
        modelo.setValueAt("REC", 2, 0);
        modelo.setValueAt(2007, 2, 1);
        modelo.setValueAt("Jaume Balagueró", 2, 2);

        modelo.setValueAt("It", 3, 0);
        modelo.setValueAt(2017, 3, 1);
        modelo.setValueAt("Andy Muschietti", 3, 2);
        
        
    }//GEN-LAST:event_jButEjemploActionPerformed

    private void jButMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButMostrarActionPerformed
        // TODO add your handling code here:
        
        switch(Integer.parseInt(jSpinnerPosicion.getValue()+""))
        {
            case 1:
                filmes[0].dibujar(0, jPanelDibujo);
                jTextAreaInfo.setText(filmes[0].mostrar());
                jSpinnerPosicion.setValue(2);
                break;
                
            case 2:
                filmes[1].dibujar(0, jPanelDibujo);
                jTextAreaInfo.setText(filmes[1].mostrar());
                jSpinnerPosicion.setValue(3);
                break;
                
            case 3:
                filmes[2].dibujar(0, jPanelDibujo);
                jTextAreaInfo.setText(filmes[2].mostrar());
                jSpinnerPosicion.setValue(4);
                break;
                
            case 4:
                filmes[3].dibujar(0, jPanelDibujo);
                jTextAreaInfo.setText(filmes[3].mostrar());
                jSpinnerPosicion.setValue(1);
                break;
                
            default:
                break;
        }

    }//GEN-LAST:event_jButMostrarActionPerformed

    private void jButDiagramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDiagramaActionPerformed
        // TODO add your handling code here:
        new PA_18131209_Frame_03a().setVisible(true);
    }//GEN-LAST:event_jButDiagramaActionPerformed

    private void jButDesfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDesfileActionPerformed
        // TODO add your handling code here:
        PA_18131209_Frame_03b FrameDesfile = new PA_18131209_Frame_03b(this);
        FrameDesfile.setVisible(true);
    }//GEN-LAST:event_jButDesfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PA_18131209_Frame_03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PA_18131209_Frame_03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PA_18131209_Frame_03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PA_18131209_Frame_03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PA_18131209_Frame_03().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButDesfile;
    private javax.swing.JButton jButDiagrama;
    private javax.swing.JButton jButEjemplo;
    private javax.swing.JButton jButGrabar;
    private javax.swing.JButton jButMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelDibujo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinnerPosicion;
    private javax.swing.JTable jTablePeliculas;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextAreaInfo;
    // End of variables declaration//GEN-END:variables
}
