package pa_18131209_proyecto_03;

/**
 *
 * @author José Misael Adame Sandoval
 */
public class PA_18131209_Frame_03b extends javax.swing.JFrame {

    /**
     * Creates new form PA_18131209_Frame_03b
     */
    Pelicula [] desfile;
    public PA_18131209_Frame_03b(PA_18131209_Frame_03 FramePrincipal) {
        initComponents();
        desfile = FramePrincipal.getInformacion();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButEmpezar = new javax.swing.JButton();
        jPanelDesfile = new javax.swing.JPanel();
        jSpinPosicion = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaInfoDesf = new javax.swing.JTextArea();
        jButVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButEmpezar.setText("Empezar");
        jButEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEmpezarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDesfileLayout = new javax.swing.GroupLayout(jPanelDesfile);
        jPanelDesfile.setLayout(jPanelDesfileLayout);
        jPanelDesfileLayout.setHorizontalGroup(
            jPanelDesfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );
        jPanelDesfileLayout.setVerticalGroup(
            jPanelDesfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        jSpinPosicion.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));

        jLabel1.setText("Posición");

        jTextAreaInfoDesf.setColumns(20);
        jTextAreaInfoDesf.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextAreaInfoDesf.setRows(5);
        jScrollPane1.setViewportView(jTextAreaInfoDesf);

        jButVolver.setText("Volver");
        jButVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDesfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButEmpezar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButVolver)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButEmpezar)
                    .addComponent(jButVolver))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDesfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEmpezarActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < desfile.length -1; i++)
        {   
            for (int j = i+1; j < desfile.length; j++) 
            {
                if (desfile[i].getDirector().compareTo(desfile[j].getDirector()) > 0) 
                {
                    Pelicula aux = desfile[i];
                    desfile[i] = desfile[j];
                    desfile[j] = aux;
                }
            }
        }
        
       
        switch(Integer.parseInt(jSpinPosicion.getValue()+""))
        {
            case 1:
                jTextAreaInfoDesf.setText(desfile[0].mostrar());
                desfile[0].mover(jPanelDesfile);
                jSpinPosicion.setValue(2);
                break;
                
            case 2:
                jTextAreaInfoDesf.setText(desfile[1].mostrar());
                desfile[1].mover(jPanelDesfile);  
                jSpinPosicion.setValue(3);
                break;
                
            case 3:
                jTextAreaInfoDesf.setText(desfile[2].mostrar());
                desfile[2].mover(jPanelDesfile);
                jSpinPosicion.setValue(4);
                break;
            case 4:
                jTextAreaInfoDesf.setText(desfile[3].mostrar());
                desfile[3].mover(jPanelDesfile);
                jSpinPosicion.setValue(1);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jButEmpezarActionPerformed

    // Para cerrar la ventana
    private void jButVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButVolverActionPerformed
     this.dispose();
       
        
    }//GEN-LAST:event_jButVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PA_18131209_Frame_03b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PA_18131209_Frame_03b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PA_18131209_Frame_03b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PA_18131209_Frame_03b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PA_18131209_Frame_03b(new PA_18131209_Frame_03()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButEmpezar;
    private javax.swing.JButton jButVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelDesfile;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinPosicion;
    private javax.swing.JTextArea jTextAreaInfoDesf;
    // End of variables declaration//GEN-END:variables
}
