package pa_18131209_proyecto_02;

import Utilerias.JTable.ColorCeldas;
import java.awt.Color;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.Random;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author José Misael Adame Sandoval
 */
public class PA_18131209_Frame_02 extends javax.swing.JFrame {

    // Se declara para poder obtener el modelo de la tabla y poder modificarlo
    DefaultTableModel modelo;
    
    public PA_18131209_Frame_02() 
    {
        initComponents();
        
        // El color de fondo del programa (gris)
        getContentPane().setBackground(new java.awt.Color(189, 187, 187));
        
        // Se asigna el modelo a la tabla de Cultivos
        modelo = (DefaultTableModel)jTableCultivos.getModel();
        
        // Muestra bordes en ambas tablas
        jTableCultivos.setShowGrid(true);
        jTableTotales.setShowGrid(true);
        
        // Deshabilita los botones
        this.deshabilitar();
    }
    
    public void colorearBlanco()
    {
        ColorCeldas celdas = new ColorCeldas(jTableCultivos);
        Empresa agricola = new Empresa(modelo.getRowCount());
        
        Cultivo mayor = new Cultivo();
        Cultivo menor = new Cultivo();
        for(int r=0; r<modelo.getRowCount(); r++) 
        {
            Produccion inicial = new Produccion((int)modelo.getValueAt(r, 1),
                                                (int)modelo.getValueAt(r, 2),
                                                (int)modelo.getValueAt(r, 3),
                                                (int)modelo.getValueAt(r, 4));
           
            
            Produccion finall = new Produccion((int)modelo.getValueAt(r, 5),
                                               (int)modelo.getValueAt(r, 6),
                                               (int)modelo.getValueAt(r, 7),
                                               (int)modelo.getValueAt(r, 8));         
                                     
            Cultivo x = new Cultivo(jTableCultivos.getValueAt(r, 0)+"", inicial, 
                                    finall, Double.parseDouble(jTableCultivos.getValueAt(r, 13)+""));
            
            agricola.setCultivo(x, r);           
        }
        
        mayor = agricola.getCultivo(0);
        menor = agricola.getCultivo(0);
        
        int men = 0, may = 0;
        
        for(int r=0; r<modelo.getRowCount(); r++) 
        {
            if(agricola.getCultivo(r).produccionMensual().librasTotales() 
               < menor.produccionMensual().librasTotales()) 
            {
                menor = agricola.getCultivo(r);
                men = r;
            }
            if(agricola.getCultivo(r).produccionMensual().librasTotales() 
               > mayor.produccionMensual().librasTotales()) 
            {
                mayor = agricola.getCultivo(r);
                may = r;
            }
            
            
        }
        celdas.repaint();
        for(int r=0; r<modelo.getColumnCount() ;r++)
        {
            celdas.addCelda(may, r, Color.white);
            celdas.addCelda(men, r, Color.white);
        }
    }  
    // metodo para la deshabilitación de botones y la tabla
    public void deshabilitar() 
    {
        jButAleatorio.setEnabled(false);
        jButCalcular.setEnabled(false);
        jButAlfabetico.setEnabled(false);
        jButDescendente.setEnabled(false);
        jButColorear.setEnabled(false);
        jTableCultivos.setEnabled(false);
    }
    
    // metodo para habilitar los botones y la tabla al dar clic en el botón de Ajustes
    public void habilitarAlAjustar() 
    {
        jButAleatorio.setEnabled(true);
        jButCalcular.setEnabled(true);
        jTableCultivos.setEnabled(true);
    }
    
    // método para habilitar los botones al dar clic en el botón de Calcular
    public void habilitarAlCalcular() 
    {
        jButDescendente.setEnabled(true);
        jButColorear.setEnabled(true);
        jButAlfabetico.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextNoCultivos = new javax.swing.JTextField();
        jButAjustar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCultivos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButAleatorio = new javax.swing.JButton();
        jButEjemplo = new javax.swing.JButton();
        jButCalcular = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTotales = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButDescendente = new javax.swing.JButton();
        jButAlfabetico = new javax.swing.JButton();
        jButColorear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pa_18131209_proyecto_02/AsignacionProyecto.jpg"))); // NOI18N

        jLabel2.setText("No. de Cultivos");

        jButAjustar.setText("Ajustar");
        jButAjustar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAjustarActionPerformed(evt);
            }
        });

        jTableCultivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cultivo", "Tonelada", "Quintal", "Arroba", "Libra", "Tonelada", "Quintal", "Arroba", "Libra", "Tonelada", "Quintal", "Arroba", "Libra", "Precio", "Importe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, true, true, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableCultivos);
        if (jTableCultivos.getColumnModel().getColumnCount() > 0) {
            jTableCultivos.getColumnModel().getColumn(0).setResizable(false);
            jTableCultivos.getColumnModel().getColumn(1).setResizable(false);
            jTableCultivos.getColumnModel().getColumn(2).setResizable(false);
            jTableCultivos.getColumnModel().getColumn(3).setResizable(false);
            jTableCultivos.getColumnModel().getColumn(4).setResizable(false);
            jTableCultivos.getColumnModel().getColumn(5).setResizable(false);
            jTableCultivos.getColumnModel().getColumn(6).setResizable(false);
            jTableCultivos.getColumnModel().getColumn(7).setResizable(false);
            jTableCultivos.getColumnModel().getColumn(8).setResizable(false);
            jTableCultivos.getColumnModel().getColumn(9).setResizable(false);
            jTableCultivos.getColumnModel().getColumn(10).setResizable(false);
            jTableCultivos.getColumnModel().getColumn(11).setResizable(false);
            jTableCultivos.getColumnModel().getColumn(12).setResizable(false);
            jTableCultivos.getColumnModel().getColumn(13).setResizable(false);
            jTableCultivos.getColumnModel().getColumn(14).setResizable(false);
            jTableCultivos.getColumnModel().getColumn(14).setPreferredWidth(100);
        }

        jLabel3.setBackground(new java.awt.Color(204, 255, 204));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Producción inicial");
        jLabel3.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(255, 204, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Producción mensual");
        jLabel4.setOpaque(true);

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Producción final");
        jLabel5.setOpaque(true);

        jButAleatorio.setText("Aleatorio");
        jButAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatorioActionPerformed(evt);
            }
        });

        jButEjemplo.setText("Ejemplo");
        jButEjemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEjemploActionPerformed(evt);
            }
        });

        jButCalcular.setText("Calcular");
        jButCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalcularActionPerformed(evt);
            }
        });

        jTableTotales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Totales", null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableTotales);
        if (jTableTotales.getColumnModel().getColumnCount() > 0) {
            jTableTotales.getColumnModel().getColumn(0).setResizable(false);
            jTableTotales.getColumnModel().getColumn(1).setResizable(false);
            jTableTotales.getColumnModel().getColumn(2).setResizable(false);
            jTableTotales.getColumnModel().getColumn(3).setResizable(false);
            jTableTotales.getColumnModel().getColumn(4).setResizable(false);
            jTableTotales.getColumnModel().getColumn(5).setResizable(false);
            jTableTotales.getColumnModel().getColumn(6).setResizable(false);
            jTableTotales.getColumnModel().getColumn(7).setResizable(false);
            jTableTotales.getColumnModel().getColumn(8).setResizable(false);
            jTableTotales.getColumnModel().getColumn(9).setResizable(false);
            jTableTotales.getColumnModel().getColumn(10).setResizable(false);
            jTableTotales.getColumnModel().getColumn(11).setResizable(false);
            jTableTotales.getColumnModel().getColumn(12).setResizable(false);
            jTableTotales.getColumnModel().getColumn(13).setResizable(false);
            jTableTotales.getColumnModel().getColumn(14).setResizable(false);
            jTableTotales.getColumnModel().getColumn(14).setPreferredWidth(100);
        }

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pa_18131209_proyecto_02/Informacion.jpg"))); // NOI18N

        jLabel7.setText("Simbología");

        jLabel8.setBackground(new java.awt.Color(255, 0, 255));
        jLabel8.setOpaque(true);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Producción Menor");

        jLabel10.setBackground(new java.awt.Color(255, 255, 0));
        jLabel10.setOpaque(true);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("Producción Mayor");

        jButDescendente.setText("Descendente");
        jButDescendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDescendenteActionPerformed(evt);
            }
        });

        jButAlfabetico.setText("Alfabetico");
        jButAlfabetico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAlfabeticoActionPerformed(evt);
            }
        });

        jButColorear.setText("Colorear");
        jButColorear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButColorearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextNoCultivos, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButAjustar)))
                                        .addGap(104, 104, 104)
                                        .addComponent(jButAleatorio)
                                        .addGap(28, 28, 28)
                                        .addComponent(jButEjemplo))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jButCalcular))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(64, 64, 64)
                                        .addComponent(jButDescendente)
                                        .addGap(29, 29, 29)
                                        .addComponent(jButAlfabetico)
                                        .addGap(35, 35, 35)
                                        .addComponent(jButColorear)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButAleatorio)
                            .addComponent(jButEjemplo)
                            .addComponent(jButCalcular)
                            .addComponent(jButAjustar)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextNoCultivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                            .addComponent(jButDescendente)
                            .addComponent(jButAlfabetico)
                            .addComponent(jButColorear))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Boton para ajustar renglones de la tabla
    private void jButAjustarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAjustarActionPerformed
        // Se asignan los renglonres de la tabla
        modelo.setRowCount(Integer.parseInt(jTextNoCultivos.getText()));
        
        // Habilita los botones y la tabla
        this.habilitarAlAjustar();
       
    }//GEN-LAST:event_jButAjustarActionPerformed

    private void jButAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatorioActionPerformed
        // TODO add your handling code here:
        DecimalFormat df = new DecimalFormat("#0.00");
        Random azar = new Random();
        
        for(int r=0; r<modelo.getRowCount(); r++) 
        {
            jTableCultivos.setValueAt(Nombre.nextNombre(), r, 0);
            
            // Produccion inicial
            jTableCultivos.setValueAt(azar.nextInt(12), r, 1); // toneladas
            jTableCultivos.setValueAt(azar.nextInt(19), r, 2); // quintales
            jTableCultivos.setValueAt(azar.nextInt(3), r, 3); // arrobas
            jTableCultivos.setValueAt(azar.nextInt(24), r, 4); // libras
            
            // Producción final
            jTableCultivos.setValueAt(12+azar.nextInt(38), r, 5); // toneladas
            jTableCultivos.setValueAt(azar.nextInt(19), r, 6); // quintales
            jTableCultivos.setValueAt(azar.nextInt(3), r, 7); // arrobas
            jTableCultivos.setValueAt(azar.nextInt(24), r, 8); // libras
            
            // importe
            double decimales = ((double)azar.nextInt(1001)/100);
            jTableCultivos.setValueAt(df.format(1+azar.nextInt(5)+decimales), r, 13); 
            
            
        }
        
        this.colorearBlanco();
        

    }//GEN-LAST:event_jButAleatorioActionPerformed

    private void jButCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalcularActionPerformed
        Locale pesos = new Locale("es","MX");
        NumberFormat nf = NumberFormat.getCurrencyInstance(pesos);
        
        Produccion inicial = new Produccion(), finall = new Produccion(); 
     
        Produccion totalInicial = new Produccion(), totalFinal = new Produccion(), totalMensual = new Produccion();
        double totalImporte = 0;
        for(int r=0; r<modelo.getRowCount(); r++) 
        {
            inicial.setToneladas(Integer.parseInt(jTableCultivos.getValueAt(r, 1)+""));
            inicial.setQuintales(Integer.parseInt(jTableCultivos.getValueAt(r, 2)+""));
            inicial.setArrobas(Integer.parseInt(jTableCultivos.getValueAt(r, 3)+""));
            inicial.setLibras(Integer.parseInt(jTableCultivos.getValueAt(r, 4)+""));
            
            finall.setToneladas(Integer.parseInt(jTableCultivos.getValueAt(r, 5)+""));
            finall.setQuintales(Integer.parseInt(jTableCultivos.getValueAt(r, 6)+""));
            finall.setArrobas(Integer.parseInt(jTableCultivos.getValueAt(r, 7)+""));
            finall.setLibras(Integer.parseInt(jTableCultivos.getValueAt(r, 8)+""));
            
            Cultivo x = new Cultivo(jTableCultivos.getValueAt(r, 0)+"",inicial, finall,Double.parseDouble(jTableCultivos.getValueAt(r, 13)+""));
            
            jTableCultivos.setValueAt(x.produccionMensual().getToneladas(), r, 9);
            jTableCultivos.setValueAt(x.produccionMensual().getQuintales(), r, 10);
            jTableCultivos.setValueAt(x.produccionMensual().getArrobas(), r, 11);
            jTableCultivos.setValueAt(x.produccionMensual().getLibras(), r, 12);
            
            jTableCultivos.setValueAt(nf.format(x.importe()), r, 14);
            
            totalFinal = totalFinal.suma(finall);
            totalInicial = totalInicial.suma(inicial);
            totalMensual = totalMensual.suma(x.produccionMensual());
            totalImporte += x.importe();
            
            
            
        }
        
        jTableTotales.setValueAt(totalInicial.getToneladas(), 0, 1);
        jTableTotales.setValueAt(totalInicial.getQuintales(), 0, 2);
        jTableTotales.setValueAt(totalInicial.getArrobas(), 0, 3);
        jTableTotales.setValueAt(totalInicial.getLibras(), 0, 4);
        
        jTableTotales.setValueAt(totalFinal.getToneladas(), 0, 5);
        jTableTotales.setValueAt(totalFinal.getQuintales(), 0, 6);
        jTableTotales.setValueAt(totalFinal.getArrobas(), 0, 7);
        jTableTotales.setValueAt(totalFinal.getLibras(), 0, 8);
        
        jTableTotales.setValueAt(totalMensual.getToneladas(), 0, 9);
        jTableTotales.setValueAt(totalMensual.getQuintales(), 0, 10);
        jTableTotales.setValueAt(totalMensual.getArrobas(), 0, 11);
        jTableTotales.setValueAt(totalMensual.getLibras(), 0, 12);
        
        jTableTotales.setValueAt(nf.format(totalImporte), 0, 14);
        
        this.habilitarAlCalcular();
       
        this.colorearBlanco();
        
    }//GEN-LAST:event_jButCalcularActionPerformed

    private void jButEjemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEjemploActionPerformed
        // TODO add your handling code here:
        
        // Asigna 4 renglones en la tabla (ejemplo)
        modelo.setRowCount(4);
        
         // Se sustituyen los valores de ejemplo en la tabla
        jTableCultivos.setValueAt("Arroz", 0, 0);
        jTableCultivos.setValueAt(7, 0, 1);
        jTableCultivos.setValueAt(18, 0, 2);
        jTableCultivos.setValueAt(2, 0, 3);
        jTableCultivos.setValueAt(22, 0, 4);
        
        jTableCultivos.setValueAt(9, 0, 5);
        jTableCultivos.setValueAt(8, 0, 6);
        jTableCultivos.setValueAt(2, 0, 7);
        jTableCultivos.setValueAt(15, 0, 8);
        jTableCultivos.setValueAt(2.58, 0, 13);

        jTableCultivos.setValueAt("Trigo", 1, 0);
        jTableCultivos.setValueAt(17, 1, 1);
        jTableCultivos.setValueAt(7, 1, 2);
        jTableCultivos.setValueAt(1, 1, 3);
        jTableCultivos.setValueAt(12, 1, 4);
        
        jTableCultivos.setValueAt(22, 1, 5);
        jTableCultivos.setValueAt(18, 1, 6);
        jTableCultivos.setValueAt(3, 1, 7);
        jTableCultivos.setValueAt(22, 1, 8);
        jTableCultivos.setValueAt(1.18, 1, 13);
        
        jTableCultivos.setValueAt("Maiz", 2, 0);
        jTableCultivos.setValueAt(24, 2, 1);
        jTableCultivos.setValueAt(5, 2, 2);
        jTableCultivos.setValueAt(3, 2, 3);
        jTableCultivos.setValueAt(22, 2, 4);
        
        jTableCultivos.setValueAt(25, 2, 5);
        jTableCultivos.setValueAt(14, 2, 6);
        jTableCultivos.setValueAt(2, 2, 7);
        jTableCultivos.setValueAt(5, 2, 8);
        jTableCultivos.setValueAt(9.14, 2, 13);
        
        jTableCultivos.setValueAt("Cebada", 3, 0);
        jTableCultivos.setValueAt(3, 3, 1);
        jTableCultivos.setValueAt(5, 3, 2);
        jTableCultivos.setValueAt(1, 3, 3);
        jTableCultivos.setValueAt(20, 3, 4);
        
        jTableCultivos.setValueAt(8, 3, 5);
        jTableCultivos.setValueAt(3, 3, 6);
        jTableCultivos.setValueAt(1, 3, 7);
        jTableCultivos.setValueAt(16, 3, 8);
        jTableCultivos.setValueAt(5.76, 3, 13);
        
        this.habilitarAlAjustar();
         this.colorearBlanco();
    }//GEN-LAST:event_jButEjemploActionPerformed

    private void jButDescendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDescendenteActionPerformed
        // TODO add your handling code here:
        Locale pesos = new Locale("es","MX");
        NumberFormat nf = NumberFormat.getCurrencyInstance(pesos);
        
        Empresa agricola = new Empresa(modelo.getRowCount());
        
        for(int r=0; r<modelo.getRowCount(); r++) 
        {
            Produccion inicial = new Produccion((int)modelo.getValueAt(r, 1),
                                                (int)modelo.getValueAt(r, 2),
                                                (int)modelo.getValueAt(r, 3),
                                                (int)modelo.getValueAt(r, 4));
           
            
            Produccion finall = new Produccion((int)modelo.getValueAt(r, 5),
                                               (int)modelo.getValueAt(r, 6),
                                               (int)modelo.getValueAt(r, 7),
                                               (int)modelo.getValueAt(r, 8));         
                                     
            Cultivo x = new Cultivo(jTableCultivos.getValueAt(r, 0)+"", inicial, 
                                    finall, Double.parseDouble(jTableCultivos.getValueAt(r, 13)+""));
            
            agricola.setCultivo(x, r);
                                     
        }
        
        agricola.ordenarProduccion();
        
        for(int r=0; r<modelo.getRowCount(); r++) 
        {
            modelo.setValueAt(agricola.getCultivo(r).getNombre(), r, 0);
            
            modelo.setValueAt(agricola.getCultivo(r).getInicial().getToneladas(), r, 1);
            modelo.setValueAt(agricola.getCultivo(r).getInicial().getQuintales(), r, 2);
            modelo.setValueAt(agricola.getCultivo(r).getInicial().getArrobas(), r, 3);
            modelo.setValueAt(agricola.getCultivo(r).getInicial().getLibras(), r, 4);
        
            modelo.setValueAt(agricola.getCultivo(r).getFinal().getToneladas(), r, 5);
            modelo.setValueAt(agricola.getCultivo(r).getFinal().getQuintales(), r, 6);
            modelo.setValueAt(agricola.getCultivo(r).getFinal().getArrobas(), r, 7);
            modelo.setValueAt(agricola.getCultivo(r).getFinal().getLibras(), r, 8);
            
            modelo.setValueAt(agricola.getCultivo(r).produccionMensual().getToneladas(), r, 9);
            modelo.setValueAt(agricola.getCultivo(r).produccionMensual().getQuintales(), r, 10);
            modelo.setValueAt(agricola.getCultivo(r).produccionMensual().getArrobas(), r, 11);
            modelo.setValueAt(agricola.getCultivo(r).produccionMensual().getLibras(), r, 12);
            
            modelo.setValueAt(agricola.getCultivo(r).getPrecio(), r, 13);
            modelo.setValueAt(nf.format(agricola.getCultivo(r).importe()), r, 14);
        }        
         this.colorearBlanco();
    }//GEN-LAST:event_jButDescendenteActionPerformed

    private void jButAlfabeticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAlfabeticoActionPerformed
        // TODO add your handling code here:
        Locale pesos = new Locale("es","MX");
        NumberFormat nf = NumberFormat.getCurrencyInstance(pesos);
        
        Empresa agricola = new Empresa(modelo.getRowCount());
        
        for(int r=0; r<modelo.getRowCount(); r++) 
        {
            Produccion inicial = new Produccion((int)modelo.getValueAt(r, 1),
                                                (int)modelo.getValueAt(r, 2),
                                                (int)modelo.getValueAt(r, 3),
                                                (int)modelo.getValueAt(r, 4));
           
            
            Produccion finall = new Produccion((int)modelo.getValueAt(r, 5),
                                               (int)modelo.getValueAt(r, 6),
                                               (int)modelo.getValueAt(r, 7),
                                               (int)modelo.getValueAt(r, 8));         
                                     
            Cultivo x = new Cultivo(jTableCultivos.getValueAt(r, 0)+"", inicial, 
                                    finall, Double.parseDouble(jTableCultivos.getValueAt(r, 13)+""));
            
            agricola.setCultivo(x, r);
                                     
        }
        
        agricola.ordenarAlfabetico();
        
        for(int r=0; r<modelo.getRowCount(); r++) 
        {
            modelo.setValueAt(agricola.getCultivo(r).getNombre(), r, 0);
            
            modelo.setValueAt(agricola.getCultivo(r).getInicial().getToneladas(), r, 1);
            modelo.setValueAt(agricola.getCultivo(r).getInicial().getQuintales(), r, 2);
            modelo.setValueAt(agricola.getCultivo(r).getInicial().getArrobas(), r, 3);
            modelo.setValueAt(agricola.getCultivo(r).getInicial().getLibras(), r, 4);
        
            modelo.setValueAt(agricola.getCultivo(r).getFinal().getToneladas(), r, 5);
            modelo.setValueAt(agricola.getCultivo(r).getFinal().getQuintales(), r, 6);
            modelo.setValueAt(agricola.getCultivo(r).getFinal().getArrobas(), r, 7);
            modelo.setValueAt(agricola.getCultivo(r).getFinal().getLibras(), r, 8);
            
            modelo.setValueAt(agricola.getCultivo(r).produccionMensual().getToneladas(), r, 9);
            modelo.setValueAt(agricola.getCultivo(r).produccionMensual().getQuintales(), r, 10);
            modelo.setValueAt(agricola.getCultivo(r).produccionMensual().getArrobas(), r, 11);
            modelo.setValueAt(agricola.getCultivo(r).produccionMensual().getLibras(), r, 12);
            
            modelo.setValueAt(agricola.getCultivo(r).getPrecio(), r, 13);
            modelo.setValueAt(nf.format(agricola.getCultivo(r).importe()), r, 14);
        }
         this.colorearBlanco();
        
    }//GEN-LAST:event_jButAlfabeticoActionPerformed

    private void jButColorearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButColorearActionPerformed
        // TODO add your handling code here:
        ColorCeldas celdas = new ColorCeldas(jTableCultivos);
        Empresa agricola = new Empresa(modelo.getRowCount());
        
        Cultivo mayor = new Cultivo();
        Cultivo menor = new Cultivo();
        for(int r=0; r<modelo.getRowCount(); r++) 
        {
            Produccion inicial = new Produccion((int)modelo.getValueAt(r, 1),
                                                (int)modelo.getValueAt(r, 2),
                                                (int)modelo.getValueAt(r, 3),
                                                (int)modelo.getValueAt(r, 4));
           
            
            Produccion finall = new Produccion((int)modelo.getValueAt(r, 5),
                                               (int)modelo.getValueAt(r, 6),
                                               (int)modelo.getValueAt(r, 7),
                                               (int)modelo.getValueAt(r, 8));         
                                     
            Cultivo x = new Cultivo(jTableCultivos.getValueAt(r, 0)+"", inicial, 
                                    finall, Double.parseDouble(jTableCultivos.getValueAt(r, 13)+""));
            
            agricola.setCultivo(x, r);           
        }
        
        mayor = agricola.getCultivo(0);
        menor = agricola.getCultivo(0);
        
        int men = 0, may = 0;
        
        for(int r=0; r<modelo.getRowCount(); r++) 
        {
            if(agricola.getCultivo(r).produccionMensual().librasTotales() 
               < menor.produccionMensual().librasTotales()) 
            {
                menor = agricola.getCultivo(r);
                men = r;
            }
            if(agricola.getCultivo(r).produccionMensual().librasTotales() 
               > mayor.produccionMensual().librasTotales()) 
            {
                mayor = agricola.getCultivo(r);
                may = r;
            }
            
            
        }
        celdas.repaint();
        for(int r=0; r<modelo.getColumnCount() ;r++)
        {
            celdas.addCelda(may, r, Color.magenta);
            celdas.addCelda(men, r, Color.yellow);
        }
    }//GEN-LAST:event_jButColorearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PA_18131209_Frame_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PA_18131209_Frame_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PA_18131209_Frame_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PA_18131209_Frame_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PA_18131209_Frame_02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAjustar;
    private javax.swing.JButton jButAleatorio;
    private javax.swing.JButton jButAlfabetico;
    private javax.swing.JButton jButCalcular;
    private javax.swing.JButton jButColorear;
    private javax.swing.JButton jButDescendente;
    private javax.swing.JButton jButEjemplo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCultivos;
    private javax.swing.JTable jTableTotales;
    private javax.swing.JTextField jTextNoCultivos;
    // End of variables declaration//GEN-END:variables
}
